### ISSUE TITLE
Collision when picking radar construction and construction pylons isn't validated when using copy paste

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#101]
You can copy-paste a Radar Construction Pylons onto another entity:

interestingly, it doesn't go into your action queue so Crtl+Z doesn't unconstruct it

test447 — Today at 11:39 PM
wonderful. it's probably either a collision issue or something with composite entities. does it happen with any other pylons?
Dodru — Today at 11:41 PM
nope
wait, it does with Construction Pylons, but not Substation Pylons
and only with Crtl+C-Crtl+V, not when held in hand via Q
test447 — Today at 11:42 PM
thanks for the info!

**Comment by daviscook477** [comment]
Potti — Today at 10:53 AM
I think i noticed something like that too… Somehow i managed to place a radar construction pylon with a 64x64 supply area, i think by first placing a substation pylon and then the construction pylon. Maybe one or either of those via ghost/copy paste

**Comment by Mernom** [comment]
One of the composite entity parts has no collision, which allows it to be ghost built with copy paste.
And the construction script probably builds the other half of the entity regardless of which was built.

If the collisionless half builds the other half on top of the substation pylon, I can see it breaking like that.

Possible fix: check the position of the collisionless half if it allows the other half to be built, if it doesn't cancel the construction.
