### ISSUE TITLE
When spaceship changes surfaces trains get set to manual.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#11]
Rseding and boskid both said that its up to modders to set it back to automatic.

**Comment by AartBluestoke** [comment]
fixed by https://github.com/EarendelDevelopers/space-exploration/commit/e979bc71089bd7720b9de4371bd98da778da5c1f#diff-980346dee247a7c1ef7b4808513faf64R779 ?
