### ISSUE TITLE
When building space buildings on the ground (using spaceship floor), module requests on ghosts aren't preserved

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#113]
This is probably because when the entity gets built we replace it with a different entity (the grounded version) and probably don't copy over the module requests (can we even do that).

Maybe fix this if that's possible.

**Comment by Mernom** [comment]
Detect the ghost being placed, and swap the ghost for the ground variant ghost with the module requests in it?

**Comment by Derunih** [comment]
Have started the fix for this on bugfix/space-swap-preserve-modules, am still working on a good way to swap the ghost for hand-placing it
