### ISSUE TITLE
only vanilla spidertron is deployed from cargo rockets when they crash land

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#116]
If its possible, make it so any item stack that will build a spidertron type entity is deployed rather than just spidertron stack.

**Comment by daviscook477** [comment]
confirmed that it is an issue with modded spidertrons and not packing tape (the discord bug report wasn't absolutely certain at first).

**Comment by daviscook477** [comment]
Shanjaq — Yesterday at 11:49 AM
Suggestion:  generically detect Spidertrons from other mods (like Spidertron Tiers) in the Cargo Rocket Payload deployment script, I tested this locally and it seems to be working.  in launchpad.lua, around line 1104:
```lua
          if tick_task.launched_inventory and tick_task.launched_inventory.valid then
            Log.trace("Distribute to pods launched_inventory")

            for key, value in pairs(tick_task.launched_contents) do
              if string.find(string.lower(key), "spider") then
                    local item_stack = tick_task.launched_inventory.find_item_stack(key)
                    
                    if(
                      item_stack.prototype
                      and item_stack.prototype.place_result
                      and item_stack.prototype.place_result.type
                      and (item_stack.prototype.place_result.type == "spider-vehicle")) then
                     spidertron_name = item_stack.prototype.place_result.name
                     
                     ...(unchanged)...

                  end
               end
```

**Comment by daviscook477** [comment]
if it doesn't break things, maybe just iterate through the item stacks in the launched inventory, rather than the launched contents to avoid an expensive find operation

**Comment by Mernom** [comment]
Make a dictionary of items which build a spider on config changed? Then check the names of the cargo against it.
