### ISSUE TITLE
if energy beam glaive new target is greater than some specific distance from current position, jump it to new position instantaneously

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#120]
why do this?

1. the player can already make the beam jump to new position instantaneously if they control it manually
2. if it doesn't do this the beam can end up taking a path directly over the player's base if it picks something across the map from its current position

**Comment by Derunih** [comment]
Have confirmed Energy Beam Glaive now "jumps" as requested

**Comment by InappropriatePenguin** [comment]
I don't believe this had been implemented. The energy beam can _appear_ to jump if it's of sufficiently high temperature, since its movement speed significantly increases.
