### ISSUE TITLE
All my mods don't currently support the expensive difficulty of technologies. 

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#125]
The tricky part will be the functions that map the tech tree and deal with prerequisites. They will need to be able to map 2 trees simultaniously.

**Comment by Mernom** [comment]
My progressive science multiplier is capable of mapping both types of the tech tree quite well.
I can donate some of the code if needed.

**Comment by BurninSun** [comment]
Can we close this with the announcement that Factorio 2.0 will make expensive difficulty a separate mod? or do we want to potentially support that mod?
