### ISSUE TITLE
Ridiculously high technology costs for Power Armor Mk3 mod

### ISSUE THREAD

**Issue by Aivech** [EarendelDevelopers/factorio-mods#126]
Items from Power Armor Mk3 seem to be gated behind high-tier techs for no obvious reason:

allows you to see in color at night - requires DSS4
![image](https://user-images.githubusercontent.com/16143392/128589533-dde601dc-66b4-4229-8c9d-6e15dfbf088b.png)

power armor Mk3 - requires DSS4 despite not being usable in space (as far as I know)
![image](https://user-images.githubusercontent.com/16143392/128589587-070e04f7-5819-49c4-b6fe-fcaff746f3ff.png)

power armor Mk4 - requires DSS1 despite not being usable in space AND being gated after the Mk3 power armor that's had DSS4 added?
![image](https://user-images.githubusercontent.com/16143392/128589610-0ce5383f-6022-4e74-ab12-a1954d078af2.png)

Reading through the mod code I can't see anywhere that specifically mentions these items, but there are a few scripts that  alter technology costs based solely on string matching against the technology name, so maybe some exceptions need to be added?

**Comment by Wiwiweb** [comment]
SE thinks this tech is way higher level than it actually is because the mod has a digit as part of its prefix.

```
  18.658 Script @__space-exploration__/prototypes/phase-3/technology-procedural.lua:72: consider tech: pamk3-pamk3
  18.658 Script @__space-exploration__/prototypes/phase-3/technology-procedural.lua:96: tech (pamk3-pamk3) level: 33
```

**Comment by waterlubber** [comment]
Why is the mod using string matching against other mods technologies in the first place? I can't imagine that 1. this is desirable to the player or 2. the few mods that interact with SpaceX couldn't be handled with a whitelist-based method.

**Comment by Mernom** [comment]
> Why is the mod using string matching against other mods technologies in the first place? I can't imagine that 1. this is desirable to the player or 2. the few mods that interact with SpaceX couldn't be handled with a whitelist-based method.

This code was meant so that we would not need to manually set the cost for every modded upgrades.
The problem is caused by the function which tried to figure out the technology's tier not accounting for the possibility that some technologies have numbers in the name besides in the end to denote tiers.
