### ISSUE TITLE
Add Ion Canister. Modify Naquium Energy Data 

### ISSUE THREAD

**Issue by fatpandana** [EarendelDevelopers/factorio-mods#137]
(from InappropriatePenguin): "Superconductive cables are byproduct from science production but not used for science."

Add Ion Canister recipe. 

Modify Naquium Energy Data in order to consume superconductive cable, to:
4x Naquium Ingot
1x Blank Data
1x Ion Canister
Yields
1x Naquium Energy data
25x contaminated scrap.

**Comment by InappropriatePenguin** [comment]
@fatpandana if we were to make this recipe consume less Naq ingots to make up for the increased ion stream cost, how many ingots should that be—perhaps 1?

**Comment by InappropriatePenguin** [comment]
Added in 0.5.84.
