### ISSUE TITLE
Logistic robots dying on top of a Meteor Point Defense will delete the Meteor Point Defense

### ISSUE THREAD

**Issue by Wiwiweb** [EarendelDevelopers/factorio-mods#139]
![image](https://user-images.githubusercontent.com/4723472/130887865-9aab8bf5-802a-4a8f-ae94-bd277c81c9b4.png)

You can see MPDs were deleted in that grid wherever a bot died. Not necessarily when they dropped a package though.

**Comment by Wiwiweb** [comment]
Fixed in 0.5.89

**Comment by AartBluestoke** [comment]
we should test other composite entities (condensers, silos, etc .)

**Comment by Wiwiweb** [comment]
It wasn't really caused by something inherent to composite entities, but by a typo in composite deletion logic. 

I think all cases were taken care of (apparently it affected add-on pylons too)
