### ISSUE TITLE
When landing a spaceship on a surface, the blueprint in toolbars are removed.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#14]
Blueprints linked to library are not affected, only blueprints in inventroy. Launching is not affected.

**Comment by EarendelGames** [comment]
This may be one of the factorio bugs that got fixed recently. Can someone check please?

**Comment by Brickcaster** [comment]
Does not occur for me.  Haven't noticed BP library links vanishing for a while and I just tested it right now and it still did not occur.

**Comment by eoraptor666** [comment]
i just checked again in game version 1.0.0 with all the latest released SE-mods: This issue still persists - stored blueprints in inventory, linked to the hotbar are removed upon landing

**Comment by EarendelGames** [comment]
My best guess on this is that the hotbar links to a specific blueprint ID. When the character is cloned the inventory is cloned, and the blueprint item is cloned with a new ID. When the player swaps characters the new character has a different blueprint ID so the blueprint in the hotbar can't be found. 
I think trying to fix this directly by updating the hotbar or swapping the items would be more difficult than just changing the spaceship-change-surface code to teleport the old character on to the clone and delete the clone.

**Comment by Derunih** [comment]
Confirmed player teleport fixes the issue
