### ISSUE TITLE
Give meteors object & player collision without preventing destroyed entity ghosts from appearing.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#145]
This will need some good testing. It needs to not break normal meteor showerd or biter meteor showers.

Currently metoers don't collide with most things becuase it prevents ghosts from being made from the game engine.

There is now a create-entity tick_task type, so that can be used to delay the genreation of a physical meteor by 1 tick.

The easiest setup is probably to make a new set of meteors with collision to replace the collision-less version after 1 tick.

**Comment by InappropriatePenguin** [comment]
This does not appear to be possible even with delayed meteor creation :(.
