### ISSUE TITLE
Whenever a structure is retargeted validate the new destination.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#148]
Currently you can use pins to change the destination of an energy beam, and probably a delivery cannon, maybe also spaceship anchoring, while scouting for the target position.

**Comment by InappropriatePenguin** [comment]
Can confirm this is an issue for delivery cannons. Working on a fix.

Have not tested with energy beams—would it matter though? Energy beams don't have a range restriction to my awareness so I'm not sure what we'd be validating.

Spaceship anchoring doesn't seem to be affected. The anchoring just stops and it goes to remote view for the pinned location.

**Comment by InappropriatePenguin** [comment]
Fixed in 0.5.92.

**Comment by InappropriatePenguin** [comment]
Turns out we _do_ need to further validate energy beam targets because of _moving_ spaceships.
