### ISSUE TITLE
Make blueprinted delivery cannons remember their target settings. 

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#15]

**Comment by Brickcaster** [comment]
Is this even possible?  I can imagine others entities that could support extra settings for blueprinting

Signal Transmission Transmitters
Signal Transmission Receivers
Cargo Landing Pads
Cargo Launch Pads

**Comment by EarendelGames** [comment]
Similar steup to AAI Programmable structures data saving. 
It uses the programmable speaker.

**Comment by daviscook477** [comment]
issue resolved
