### ISSUE TITLE
map-settings and map-gen-settings sample

### ISSUE THREAD

**Issue by SemicolonStruggles** [EarendelDevelopers/factorio-mods#151]
I'm trying to setup a SE server, I've installed everything correctly and its working just fine with the exception that I'm getting a message that I'm running at a non-default difficulty setting.

I've looked into the SE Default settings as described on the wiki and I'm able to use those on a single player map, but I've got no idea on how to use these settings on a headless server. I've tried making a single player map and looked into the save file to see if I could copy over the settings files, but single player settings seem to be stored in a different format than the files on a headless server.

Could someone please provide me with a **map-settings** and **map-gen-settings** file containing the SE Default settings that are compatible with the Factorio headless server?

**Comment by Wiwiweb** [comment]
I'm not super familiar with headless server setup, but I think you can also load a save file.

Create your single player file with the right map generation and immediately save.

Then instead of `--create` use `--start-server`:

```
    ./bin/x64/factorio --start-server ./saves/<mysavefile>.zip
```

**Comment by InappropriatePenguin** [comment]
Did you manage to resolve your issue, @SemicolonStruggles?

**Comment by aznkvaj** [comment]
Here is a file I have generated using the Default Space Exploration settings for headless server.

[Factorio_SE_headless_server_mapgen.zip](https://github.com/EarendelDevelopers/factorio-mods/files/8055511/Factorio_SE_headless_server_mapgen.zip)
