### ISSUE TITLE
Crash when dying while shooting tesla gun

### ISSUE THREAD

**Issue by rdenison** [EarendelDevelopers/factorio-mods#153]
The mod Space Exploration (0.5.92) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
Given entity doesn't exist anymore.
stack traceback:
	[C]: in function 'damage'
	__space-exploration__/scripts/weapon.lua:298: in function 'chain_beam'
	__space-exploration__/control.lua:1234: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

I went into a vault (first one!) and started shooting all the biters with my new tesla gun. After killing quite a few of them they were able to kill me immediately crashing the game. I have barely any experience reporting bugs, so if you need more information, let me know.

Luckily I had saved right before entering so i was eventually able to clear the vault. Thanks for the great mod!

**Comment by Wiwiweb** [comment]
Thanks for the report!
