### ISSUE TITLE
Overly long ship names break GUI in various ways

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#155]
Using extremely long ship names will cause ship console GUI to be stretched to accommodate even for ships that are not the overly long named ship. I have copy/pasted 1MB worth of text into a ship name and this is the results.

Note the scrollbar at the bottom of the GUI window even though this is a short named ship.
![image](https://user-images.githubusercontent.com/12116957/143394038-02c25a3b-d766-47f0-bdaf-70637b1ef53c.png)

Also, the universe explorer has the ship name overlaying the other columns. 
![image](https://user-images.githubusercontent.com/12116957/143394264-cf827b4c-2faf-4913-882a-b49772fba1f9.png)

Lastly, opening the ship GUI, even with a shortly named ship, causes fps to drop significantly. eg. from 60 to 1.

As part of a potential fix, I would be careful about limiting the text length as using item tags may push up against any limit very quickly. The name should just always display as much as possible and finish with a "..." similar to the various train stop GUIs.

**Comment by InappropriatePenguin** [comment]
I cannot reproduce this as of 0.6.90.
