### ISSUE TITLE
Bring a functional water pump into space and other surfaces

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#159]
An offshore water pump can have landfill placed underneath it to turn it into a water well. Then it is possible to place spaceship flooring underneath that water well, build a spaceship around it, and launch it into space. The water well will continue to output water on the flying spaceship and when docked at other locations including in space.

**Comment by Derunih** [comment]
Spaceship flooring no longer placeable under offshore pumps, even in waterwell version
