### ISSUE TITLE
Spidertron waypoint coordinates are copied incorrectly on spaceship launch

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#160]
If a spidertron is on a spaceship and is given a movement command, it gets a waypoint set and starts walking. With that waypoint still set when the spaceship launches/lands, the waypoint is copied to the new surface using the coordinate frame of the surface and not of the spaceship. For example, a spidertron told to move 10 units north of center of spaceship, then spaceship docks before the spidertron finishes moving, the spidertron will now attempt to move to a point 10 units north of the center of the surface just docked on. It should either clear the movement commands (which may cause issues with other mods that allow roaming spidertrons) or adjust the coordinate frame of the waypoint to match the coordinate frame of the now docked spaceship.

**Comment by Derunih** [comment]
Have confirmed movement commands are now converted to relative coordinates
