### ISSUE TITLE
Landfill under a spaceship landing appears as deconstructable

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#165]
Place landfill, land a spaceship on the landfill, then launch the spaceship. The landfill underneath where the spaceship was is now selectable with the deconstruction planner though it is not actually deconstructed:
![image](https://user-images.githubusercontent.com/12116957/143403472-b6f4d5d1-f51a-46b5-86f9-552c41867551.png)
Result is that bots will go out and hit each of the deconstructable tiles, but will not actually pick up or deliver anything. Those tiles remain selectable with the deconstruction planner.

**Comment by Mernom** [comment]
I would say it's a vanilla bug? Teleporting deconstructible tiles doesn't clear the property from the non-deconstructible tiles below?

**Comment by InappropriatePenguin** [comment]
I suppose it might be. If so, we should be able to reproduce it in vanilla using editor cloning.

**Comment by Mernom** [comment]
Looking at the code, se doesn't do anything special, just set_tiles.
Testing should be as simple as setting a bunch of concrete into landfill, I think.
I wonder, would it also work with other tiles, if they can be placed? Would it work if you set it to water, if you got a waterfill mod?
Would it work with normal tiles as well?

**Comment by Mernom** [comment]
If I had to guess, I'd say that whenever a deconstructible tile is created, a deconstruction tile proxy is created over that area, and set_tiles doesn't bother clearing it up later.

**Comment by Derunih** [comment]
I am not quite sure what specific combination of variables sets it, but clearing the hidden_tile after set_tile is what prevents the deconstruct. If you set landfill to landfill using the console, the same bug occurs for some reason, but set_hidden_tile to nil fixes it. Pull request with a fix has been made
