### ISSUE TITLE
Repeatedly enter/exit capsule during launch animation allows launching multiple times

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#166]
When in a space capsule, during the launch animation, its possible to press enter to exit, then enter again to reenter the space capsule. That will cause the Launch GUI to display again. Pressing the Launch button resets the launch animation. This process is repeatable indefinitely. A side effect is that, upon launching, there is a small circular light left behind which is normally cleaned up after launch completes. However, by using this bug, there are lights and sound effects left behind forever:
![image](https://user-images.githubusercontent.com/12116957/143405290-6d637860-1b44-49c7-a271-146c6fcd0aad.png)
The brighter lights correspond to locations where the capsule was repeatedly launched without moving. Placing the camera in this location results in the launch sound effect being played very loudly, repeatedly, forever.

**Comment by InappropriatePenguin** [comment]
Thanks for the report. There's work done to fix this and a host of similar bugs that you've reported (related to the player doing things during the launch animation), though it won't apply to cargo rockets right away.
