### ISSUE TITLE
Player "discovering" spaceships

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#167]
Sometimes boarding a spaceship causes a message to popup in the console that the player has "Discovered a new spaceship." Save attached. Player is located on the ship Eris which has rendezvoused with the ship Heron. Using the Eris spaceship console to board the ship Heron causes the message to pop up.
https://drive.google.com/file/d/1sLp-XTBXzY5xb6Do39z9HJNOIpkyiWP7/view?usp=sharing
Also, possibly unrelated, note that in the universe explorer, some (but not all) ships are flagged as having been visited by the player. However, the ship Heron is NOT flagged nor will it become flagged when "discovering" it as above.

**Comment by InappropriatePenguin** [comment]
Thanks for the report—could you make your shared link not require individual access permission?

**Comment by BurninSun** [comment]
> Thanks for the report—could you make your shared link not require individual access permission?

Done, sorry.

**Comment by InappropriatePenguin** [comment]
No worries. The save was very helpful to have.

The issue will get closed once the fix is merged.
