### ISSUE TITLE
Trains "leave" their station on spaceship land

### ISSUE THREAD

**Issue by RoboGuthix** [EarendelDevelopers/factorio-mods#172]
I have a train configured to wait at a stop on a spaceship based on a circuit condition, which fires for 1 tick when the spaceship lands.

While the ship is in transit, the train is correctly "at" its station, i.e. it reports that it is waiting for the circuit condition. When the ship lands, the train seems to have "inched slightly forward": it is trying to go to the station it is sat at and will say no route if there are no other stations of the same name available.

I would expect the train to stay waiting at the station as the ship lands.

Just want to add that we've loved this mod and I can't imagine how much work went into it!

**Comment by InappropriatePenguin** [comment]
Thank you for the report @RoboGuthix.

Unfortunately, this is a base game issue with cloning trains under certain conditions which I suspect you have. You can see the bug report [here](https://forums.factorio.com/viewtopic.php?f=7&t=100255&p=554284&hilit=train#p554284) for more details.

**Comment by RoboGuthix** [comment]
Thanks, that looks like exactly it, with the caveat that my rails are completely straight. Will hope for a fix but workaround in the meantime :)

**Comment by InappropriatePenguin** [comment]
Sounds good. I'm going to go ahead and close this issue for now. If someone has an idea for a workable way to address this on SE's end, please feel free to reopen.
