### ISSUE TITLE
Placing a water tile on a waterless planet crash

### ISSUE THREAD

**Issue by robotman2412** [EarendelDevelopers/factorio-mods#175]
Relevant mods:
- Space exploration v0.5.100
- Waterwill v1.1.0 (https://mods.factorio.com/mod/Waterfill_v17)

Steps to reproduce:
1. Travel to a waterless planet.
2. Place waterfill manually, or by robot.
3. Observe the crash.

The crash seems to be caused by a nil value being used somewhere.

**Comment by InappropriatePenguin** [comment]
Could you verify if this issue still exists with the latest version of SE (0.5.103)? IIRC, this was fixed in 0.5.101.

**Comment by robotman2412** [comment]
It's fixed in the latest version, both player and robot.
