### ISSUE TITLE
K2 Spidertron unfueled after auto-deploying

### ISSUE THREAD

**Issue by Bobsson** [EarendelDevelopers/factorio-mods#176]
When playing with K2, spidertrons need to be fueled with nuclear fuel.  However, when one is auto-deployed by a rocket that doesn't hit a landing pad, the fuel isn't being automatically loaded in the way that the construction bots are.  

The workaround is to hope that the container containing the fuel lands within the spider's logistic zone, and deconstructing it loads them in just fine, but if it falls too far away, you may be hosed.

**Comment by InappropriatePenguin** [comment]
Resolved for 0.5.104.
