### ISSUE TITLE
Mod-Compatibility in spaceship-clone.lua

### ISSUE THREAD

**Issue by S3bulon** [EarendelDevelopers/factorio-mods#185]
My own mod uses the `on_player_driving_changed_state`-Event to destroy the previously used vehicle.
This clashes with `spaceship-clone.lua` Line 149 (Version 0.5.107) in the function `clone` which accesses the vehicle after `vehicle.set_driver(nil)`.

A Fix for this would be setting the driver to nil after accessing the data.
(Passengers are not allowed for my mod.)
It worked for me after modifying the script locally.

Thanks in advance.

**Comment by InappropriatePenguin** [comment]
Going to close this as the code around launching spaceships has changed in 0.6.95 to no longer eject drivers from cars and spidertrons.
