### ISSUE TITLE
space clamp is invisible and can only be placed facing to the right

### ISSUE THREAD

**Issue by purdueme91** [EarendelDevelopers/factorio-mods#187]
Very close to end game and updated to latest SE mods several weeks ago.  First time trying to place a new space clamp since updating and it is invisible before placement.  Always comes in facing to the right.  Tried rotating before placing and doesn't help.  Happened on all surfaces I've tried so far: land, platform and spaceship floor.   Have not tried copying and pasting clamps yet as a workaround.

**Comment by boogieman1402** [comment]
I've run into this problem as well, but I've found if I save and load the game (don't even need to restart factorio), the clamp outline is visible again.
