### ISSUE TITLE
Make a an addon jetpack character sprite that can be rendered over ground objects

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#19]
Character sprites don't support rander layer.

Make the jetpack character invisible.
Make an 8-direction character sprite in a static flying pose. 
Attach the sprite to the character using the rendering API with a higher than normal render layer.
We will lose animations, and armor variations, and weapon variation but only while flying. 
Sprite should have the weapon drawn.

**Comment by InappropriatePenguin** [comment]
Resolved in 0.3.1.
