### ISSUE TITLE
Core mining drill doesn't disable itself when marked for deconstruction.

### ISSUE THREAD

**Issue by Padacuw** [EarendelDevelopers/factorio-mods#190]
In the base game burner and electric miners disable themselves when they are marked for construction with the deconstruction planner. The core mining drill doesn't follow this behavior. This is kinda annoying as this means you can't disable your core mining drills at long range if you are having electricity problems. https://media.discordapp.net/attachments/364520505329451029/959932708715364372/20220402223923_1.jpg?width=886&height=498

**Comment by InappropriatePenguin** [comment]
Thank you for the report. This should be fixed for the next release.
