### ISSUE TITLE
Someone reported that they deleted Foenestra using the delete surface button in Universe Explorer. 

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#191]
That zone is supposed to be protected from deletion. They recently updated their mod version, but it might have been a very old version when the surface was deleted so maybe it has already been fixed, but should be tested.

**Comment by InappropriatePenguin** [comment]
Tested—not able to reproduce the issue. Console message gets printed and the surface doesn't get deleted.
