### ISSUE TITLE
[0.5.113] Some surfaces have lost daylight cycle

### ISSUE THREAD

**Issue by thezero** [EarendelDevelopers/factorio-mods#196]
After updating to 0.5.113 + Postprocess 0.5.30, some of surfaces (including Nauvis) have lost their day-light cycle. Plenty of other mods but downgrading to previous version + loading the save works without issues.

Proof: 
![image](https://user-images.githubusercontent.com/496534/164043861-11cca68e-0c7e-4d20-9b97-1ed792b9010a.png)

**Comment by Wiwiweb** [comment]
Confirmed, that'll be fixed next version. We'll unfreeze planets affected by this bug too.

**Comment by Wiwiweb** [comment]
Fixed in 0.5.114
