### ISSUE TITLE
AII Signal Transmission: German translation

### ISSUE THREAD

**Issue by ST-DDT** [EarendelDevelopers/factorio-mods#198]
Here the German (`de`) translation:

[aii-signal-strings.cfg.txt](https://github.com/EarendelDevelopers/factorio-mods/files/8747352/aii-signal-strings.cfg.txt)

(I had to rename the file, to be able to upload them here)

Thanks for this amazing mod.
Without it SpaceExploration would be a very big hassle.

**Comment by InappropriatePenguin** [comment]
Thanks for your contribution 👍🏼 This should be in the next release.
