### ISSUE TITLE
Cargo rocket doesn't load Cargo Rocket Sections or Space Capsule if already at full cargo

### ISSUE THREAD

**Issue by CostaTC** [EarendelDevelopers/factorio-mods#201]
As the title says, if the cargo rocket already has full cargo then the Cargo Rocket Sections and/or Space Capsule cant be placed inside the rocket.

Easily able to replicate by:
- Filling rocket with non-rocket sections or capsules
- Attempting to place sections or a capsule in via a player or arm

I assume this is due to an under-the-hood limitation from the base game so I'm not sure if this is able to be fixed.
I think a good alternative is to output when the rocket has been built in the silo - that way I can hold off loading the rocket via circuits.

**Comment by Wiwiweb** [comment]
Yep, it's a limitation, and yep, we already do that signal.
![image](https://user-images.githubusercontent.com/4723472/171989956-e651e65d-24f5-463e-b20d-93ea99cad953.png)
