### ISSUE TITLE
Show alert messages for surfaces that have meteor defenses on them. 

### ISSUE THREAD

**Issue by megaicemage** [EarendelDevelopers/factorio-mods#203]
Currently meteor alert messages are only displayed for the surface the player is currently on. This means that a player's outpost that is failing to defend itself will not warn the player. 

This is a root cause for https://github.com/EarendelDevelopers/factorio-mods/issues/29. 

After talking with test447 on the discord this is the solution he came up with. Since meteor showers already use meteor defenses to calculate their outcome we can use that same information to decide if the player should be notified of the result. If the player has defenses on the surface then we can assume that it is important to them and they want to be notified of the result.

**Comment by BurninSun** [comment]
Fixed in 0.6.113
