### ISSUE TITLE
Items delivered by bots while in nav sat view don't respect "Always keep players inventory sorted"

### ISSUE THREAD

**Issue by Cardanis** [EarendelDevelopers/factorio-mods#214]
If you enter a logistics network and bots start bringing you items, but you then enter nav sat view, when you come back any items delivered to your player will be at the end of your inventory instead of auto sorted.  Clicking any of them causes it to auto sort as expected.

**Comment by tburrows13** [comment]
And this should be solved by calling https://lua-api.factorio.com/latest/LuaInventory.html#LuaInventory.sort_and_merge when exiting the navsat, if https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.auto_sort_main_inventory is true.
