### ISSUE TITLE
Manually riding space elevator distance limit only applies in east and south directions

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#215]
Build space elevator, try to manually ride it to the other end. If the player is east and/or south of the elevator, there is a check that the player is within 15 and will generate an error if the player is too far away. If the player is north or west of the elevator, the distance no longer matters and the player will be transported regardless of distance from the elevator.

**Comment by Wiwiweb** [comment]
This will be a key technique for the SE speedrun in SGDQ 2026. 😄
