### ISSUE TITLE
Migrating from 0.5x to 0.6x appears to respawn biters in the pyramids

### ISSUE THREAD

**Issue by BurninSun** [EarendelDevelopers/factorio-mods#220]
Migrated from 0.5.97 to 0.6.78 and the biters and nests within the pyramids were respawned. The treasure chest located within was not refilled.

**Comment by InappropriatePenguin** [comment]
I couldn't reproduce this using my 0.5.103 savefile (and I don't believe the 0.5.97⟶0.5.103 migration is the problem). The only way I get them to respawn is by deleting the vault surface using the Editor (or via command). Are you sure you didn't inadvertently delete a vault surface?

**Comment by BurninSun** [comment]
After checking some old saves synced with old versions, apparently this happened prior to 0.6x. Unfortunately, I don't have any saves prior to SE 0.5.97 and my oldest save has the biters respawned so I have no idea when or how it happened. I do know they were cleared out at one point though as I have screenshots for the glyphs. I don't believe I deleted the vault surface as I don't normally use the editor or console commands on my main game.

I'll go ahead and close this since I have no way to reproduce or glean any further information.
