### ISSUE TITLE
Core seam can open on the edge (maybe even outside) of a planet.

### ISSUE THREAD

**Issue by Exanc** [EarendelDevelopers/factorio-mods#225]
I've just updated my Space Exploration world from 0.5.116 to 0.6.80, and a core seam has appeard on the very edge of nauvis. This doesn't look right.

![screenshot-tick-15920977](https://user-images.githubusercontent.com/43091560/182240577-19aa3cee-2468-4856-87ef-51387ef95b83.png)

**Comment by InappropriatePenguin** [comment]
Hmm, you're not supposed to have such a straight margin for Nauvis in the first place. Did you happen to set a width and height in advanced settings when starting the game?

**Comment by Exanc** [comment]
Yeah, at first though it was normal, but when i did my first surface scan i saw that something was wrong. Turns out I limited it to 1000*1000 on accident wich is real disadvantage when trying to biuld a base.

**Comment by Exanc** [comment]
And it might also be the source of the bug now that I think of it.

**Comment by InappropriatePenguin** [comment]
Yes, that's very likely the cause. We'll probably change it so that those width and height settings are not used, as many players don't realize their implications until much later in the game.

In the meantime, if you'd like to fix your world's mapgen settings, let me know. Best to find me in the SE Discord if you have an account.

**Comment by Exanc** [comment]
Yeah, I only need to regenerate Nauvis and already found a way to do it.
Just need to change the map-gen-settings in the editor and delete empty chunks.

**Comment by InappropriatePenguin** [comment]
You can always use "Trim surface" in the Universe Explorer to delete those empty chunks, once you've changed the map-gen settings.

**Comment by Exanc** [comment]
Thats another solution yeah.

Damm, if transitioning from 0.5 to 0.6 wasn't long enough, now I need to reinstall defences.
