### ISSUE TITLE
Managed to crash SE by using an energy glaive on the very emitter providing the glaive.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#229]
The mod Space Exploration (0.6.81) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
__space-exploration__/scripts/energy-beam.lua:463: attempt to index field 'glaive_beam' (a nil value)
stack traceback:
    __space-exploration__/scripts/energy-beam.lua:463: in function 'beam_move'
    __space-exploration__/scripts/energy-beam.lua:532: in function 'callback'
    __space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by BurninSun** [comment]
Fixed in v0.6.86
