### ISSUE TITLE
Train wagon excess items are destroyed when passing through Space Elevator

### ISSUE THREAD

**Issue by nixxquality** [EarendelDevelopers/factorio-mods#234]
Here's a more minor issue that I'll drop while I'm here.

We were adjusting train wagons to get ratios right and noticed a bug. If you've loaded up a wagon with items and afterwards change the max limit by using the red cross thing, the items still sit in the red slots.
However, when that train passes through a Space Elevator, the items in the red slots will disappear.

**Comment by BurninSun** [comment]
Fixed in v0.6.86
