### ISSUE TITLE
SE: "Confirm hostile extinction" button dose not update the ui

### ISSUE THREAD

**Issue by TheHllm** [EarendelDevelopers/factorio-mods#235]
When the "Confirm hostile extinction" button is pressed and the action is successfully applied, the corrosponging threat level is not updated in the ui.

**Comment by BurninSun** [comment]
Just tried this, seems to work fine. The instant it confirms extinction, the threat level on the right updates, and the threat level the sorting list did as well. Are you sure it actually confirmed extinction?

**Comment by TheHllm** [comment]
Hm, i guess there are multiple places that show the threat, i was tanking about right here:
![image](https://user-images.githubusercontent.com/28152920/185510463-65e69451-9343-4c7a-8376-0266a0d92850.png)

And yes i confirmed it and everything but, was a bit startled when the threat did not update, and then figured it was just a ui issue.

But from what i can gather you are talking about this view?
![image](https://user-images.githubusercontent.com/28152920/185510168-deb02353-2456-4323-9072-09bb939d4d0c.png)

I dont know if that one works correctly or not, but it seems likely that with some many places that need to be updated one could be over looked.

**Comment by BurninSun** [comment]
Fixed in v0.6.86
