### ISSUE TITLE
SE crash after first rocket launch

### ISSUE THREAD

**Issue by rampagggg** [EarendelDevelopers/factorio-mods#236]
Error while running event space-exploration::on_tick (ID 0)
position: 16081394.347524 is out of range
stack traceback:
	[C]: in function 'chart'
	__space-exploration__/scripts/scanner.lua:38: in function 'chart_position'
	__space-exploration__/control.lua:1496: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

Please help, i'm playing SE+K2, i might need to turn off something? Crashing after i launch rocket in space first time.

**Comment by InappropriatePenguin** [comment]
Disable the mod "Construction Drones" and then launch your first rocket. You can re-enable it afterwards if you want.

**Comment by rampagggg** [comment]
> Disable the mod "Construction Drones" and then launch your first rocket. You can re-enable it afterwards if you want.

Wow, thanks a lot, it helped!
