### ISSUE TITLE
Walls block spitters does not work on Natural Evolution Enemies

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#24]

**Comment by Derunih** [comment]
Looking into this - NE looks like it isn't updated for Factorio 1.0 or 1.1, should I look into compatibility for the externally patched versions?

**Comment by Wiwiweb** [comment]
Haven't seen anyone use NE recently. It hasn't been updated in 20 months. It's probably safe to close this ticket imo.
