### ISSUE TITLE
Can't land on another planet 

### ISSUE THREAD

**Issue by YannickStumpf** [EarendelDevelopers/factorio-mods#244]
So everytime I try to travel to another planet, i get this error, I have no Idea why, can someone help me out.
If more details are needed I can provide logs etc

Error while running event space-exploration::on_tick (ID 0)
__space-exploration__/scripts/launchpad.lua:1294: attempt to index local 'container' (a nil value)
stack traceback:
	__space-exploration__/scripts/launchpad.lua:1294: in function 'tick_journey_land'
	__space-exploration__/scripts/launchpad.lua:1322: in function 'tick_journey'
	__space-exploration__/control.lua:1392: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by InappropriatePenguin** [comment]
What version of SE are you on?

**Comment by YannickStumpf** [comment]
Im on version 0.6.78

**Comment by InappropriatePenguin** [comment]
You have AAI Programmable Vehicles too, I'm guessing?

If you do, set the Construction denial range in map settings to 0 and you'll be able to land.

**Comment by InappropriatePenguin** [comment]
Closing this due to lack of response.
