### ISSUE TITLE
Space Elevator Problem When Next Stop has Train Limit

### ISSUE THREAD

**Issue by bcwhite-code** [EarendelDevelopers/factorio-mods#248]
I had two identical stations just outside the space elevator, both with a "train limit" of one (1) in an attempt to ensure they would load-balance.  As the train leaves the elevator, it briefly stops after each car saying "destination full" then continues only to repeat with the next car.  Once the train is fully clear of the elevator, it continues fine.

For now, I've just removed the train-limit on both stations and it's working fine.

**Comment by Wiwiweb** [comment]
That has a fix on the way.
