### ISSUE TITLE
Swarm Safety 2 technology has wrong title.

### ISSUE THREAD

**Issue by charpercyr** [EarendelDevelopers/factorio-mods#249]
Swarm Safety 2 technology has wrong title. It says "Swarm Safety 3" instead of "Swarm Safety 2".
<img width="537" alt="Screenshot 2022-10-16 215042" src="https://user-images.githubusercontent.com/6374219/196091947-97c551b7-9844-4fd1-a6e4-b08902a832a6.png">

**Comment by BurninSun** [comment]
That is swarm safety 3. This is swarm safety 2:
![image](https://user-images.githubusercontent.com/12116957/196093218-c8cec2a7-d2bc-4c7a-94f3-852c97ad9cd4.png)
