### ISSUE TITLE
Zone discovery resource preference not taken into account during map generation

### ISSUE THREAD

**Issue by veleritas** [EarendelDevelopers/factorio-mods#251]
Hi, I believe I have found a bug with map generation not taking zone discovery preferences into account.

I have a planet in my Nauvis solar system (Atonoy) which the tooltip in the universe explorer states has vulcanite at 872% frequency and 367% size. Based on these values, I expect vulcanite to be pretty common on the planet's surface, but after scanning the entire planet, I can barely find any patches of vulcanite.

This is strange to me. Either the tooltip in the universe explorer is wrong, or the map generation is somehow not respecting the tooltip's stated values. The reason I suggest that it is due to the zone discovery preferences is because this planet was discovered when I had the "vulcanite preference" set.

I can provide the game save files and screenshots. I am playing on the latest 0.6 version of SE.

**Comment by InappropriatePenguin** [comment]
The resource bars in the universe explorer reflect the map gen settings for a given surface. Some resources like vulcanite or cryolite are restricted to certain types of terrain [volcanic for vulcanite, frozen from cryonite]. If a planet doesn't end up with that kind of terrain for whatever reason, then that resource won't spawn with the estimated frequency. This is explained in the tooltip for "Resource probabilities are estimates" line below the resource bars.
