### ISSUE TITLE
"Alien Biomes" don't load after update

### ISSUE THREAD

**Issue by Dominiquini** [EarendelDevelopers/factorio-mods#252]
After the last update (0.6.7 -> 0.6.8), my map don't load anymore!

>  ....
>  219.597 Factorio initialised
>  219.604 Steam Storage Quota: 4676/4768
>  323.160 Loading map C:\Users\Rafael Dominiquini\AppData\Roaming\Factorio\saves\Barbatron.zip: 95760926 bytes.
>  323.317 Loading level.dat: 651745364 bytes.
>  323.321 Info Scenario.cpp:199: Map version 1.1.70-1
>  327.709 Warning Map.cpp:347: Map loading failed: bad allocation
>  329.489 Error AppManagerStates.cpp:1566: bad allocation

When I rollback to 0.6.7, the map load normally!

* I don't have IR or K2 (Reading the changelog, the last update appears to only touch things related to this mods!) installed on my game!

Thanks

**Comment by Wiwiweb** [comment]
Can you upload that save file?

**Comment by Dominiquini** [comment]
Strange. I tried again and now everything was working! I don't change anything. Only update again this mod...

I think I can close this issue!

Thanks.
