### ISSUE TITLE
Crash when a cargo rocket auto-deploys a modded spidertron with too small of an inventory

### ISSUE THREAD

**Issue by Blackraz0r** [EarendelDevelopers/factorio-mods#257]
This error comes up while trying to land on another Planet.
Its somehow strange because i was able to land on other planets too.

The mod Space Exploration (0.6.90) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
Index out of inventory bounds.
stack traceback:
	[C]: in function 'set_filter'
	__space-exploration__/scripts/launchpad.lua:1151: in function 'tick_journey_land'
	__space-exploration__/scripts/launchpad.lua:1264: in function 'tick_journey'
	__space-exploration__/control.lua:1405: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by Blackraz0r** [comment]
I updated to 0.6.92 right now, still same issue.

The mod Space Exploration (0.6.92) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
Index out of inventory bounds.
stack traceback:
	[C]: in function 'set_filter'
	__space-exploration__/scripts/launchpad.lua:1185: in function 'tick_journey_land'
	__space-exploration__/scripts/launchpad.lua:1298: in function 'tick_journey'
	__space-exploration__/control.lua:1406: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

Want to have the Save an the logs?

**Comment by Blackraz0r** [comment]
Next Try:
it only happens when i put a spidertron in the rocket. (doesn't matter ef equipped or empty)
Without spidey, it works fine. Seems like i have to go by foot now for new planets.

BTW, maybe it has something to to with it, on the planet there is one of these alien pyramid thingies. ^^

**Comment by InappropriatePenguin** [comment]
@Blackraz0r, are you using spidertrons with a much smaller inventory than vanilla?

**Comment by Blackraz0r** [comment]
Oh yeah, maybe, im using the "Spidertron Tiers Fix K2 Space Exploration" Mod wich adds a few tired ST i tried launching with the mk0 one wich has a smaller Invetory and grid size.

But on the other hand i allready launched spideys to a few other worlds. so i thought it might be something else than the spideys ^^

**Comment by InappropriatePenguin** [comment]
The stack trace suggests that it's the small inventory size of your spidertron that was causing the issue.

Because the spidertron you packed had a small inventory and didn't have any filtered slots, SE tried to pack it with its default preset of items, which happens to be too big for it.

The simplest solution for you right now would be to pre-filter your spidertron's inventory with the items you want it to pick up from the rocket. You must at least have one of the spidertron's inventory slots filtered, so that SE doesn't fall back to its preset, retriggering the error.

**Comment by Blackraz0r** [comment]
Oh nice i see! maybe the prior launches were simply not as packed as the last one.

ill try it with prefiltering for bots, solar and some other stuff and then ill test it again. Thank you so far!
I'll report how that goes ;)

**Comment by InappropriatePenguin** [comment]
You're welcome :)

It is fixed for the next release either way.

**Comment by Blackraz0r** [comment]
oh that was fast. btw it works. you were right! thank you buddy!

How is it going to be fixed? like respect the maximum inventory size of the spidey?

**Comment by InappropriatePenguin** [comment]
Great. Yes, the inventory size of the auto-deployed spidertron is checked and inventory filters are only set _up to_ that limit.
