### ISSUE TITLE
jetpack_0.3.8 jetpack-speed-reduces-shields settings description key mismatch

### ISSUE THREAD

**Issue by ST-DDT** [EarendelDevelopers/factorio-mods#259]
The description for one of the mod settings uses the wrong key:

````ini
[mod-setting-name]
jetpack-speed-reduces-shields=Speed reduces shields

[mod-setting-description]
jetpack-speed-damages-shields=The amount that speed reduces your current shield value.
````

`reduces` vs `damages`

Discovered while translating the mod to [German](https://discord.com/channels/419526714721566720/572104426333143050/1055928575825543219).

**Affects versions:**

- jetpack_0.3.8

Merry Xmas everyone

**Comment by Wiwiweb** [comment]
Good catch 👍 Fixed
