### ISSUE TITLE
Space elevator power accumulation goes negative

### ISSUE THREAD

**Issue by amoscao** [EarendelDevelopers/factorio-mods#263]
Disconnecting constructed space elevator results in `Energy: X MJ / 10,000MJ`, where `X` continues to decrease past 0.

Steps to reproduce:

1. Set up space elevator with power connected to source in orbit and sink on planet surface.
Space elevator settings prior to disconnect:
![image](https://user-images.githubusercontent.com/10836807/209569172-a9db8de6-8e0d-4d97-bb32-986b6eb13799.png)

2. Disconnect space elevator from all power in orbit, allowing space elevator to start discharging accumulator:
![image](https://user-images.githubusercontent.com/10836807/209569598-b7e8bf17-5f07-47fb-99b6-5667b3d228a8.png)

3. Elevator will continue to discharge into a negative value:
![image](https://user-images.githubusercontent.com/10836807/209570773-ad9a82b4-1318-4ade-a782-0becb4ad648a.png)

**Comment by BurninSun** [comment]
Gave this some testing. The electricity transfer doesn't matter. Its just after the elevator is fully built and functional, it has a scripted power draw. That power draw doesn't check for < 0 and just keeps going when disconnected from a power grid. Do we want the cable to break or just stop draining power when it hits 0? It already stops being usable by trains at 2500MJ and players at 0.

**Comment by Wiwiweb** [comment]
Fixed in 0.6.102
