### ISSUE TITLE
Landing ship on a very rocky landscape seems to crash the engine.

### ISSUE THREAD

**Issue by Runaes** [EarendelDevelopers/factorio-mods#269]
Anchoring ship on vulcanite planet and got a non recoverable error.

The mod Space Exploration (0.6.95) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_gui_click (ID 1)
The mod Filter Combinator (1.1.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Filter_Combinator::script_raised_destroy (ID 80)
__Filter_Combinator__/script/entity.lua:76: attempt to index a nil value
stack traceback:
	__Filter_Combinator__/script/entity.lua:76: in function <__Filter_Combinator__/script/entity.lua:73>
stack traceback:
	[C]: in function 'destroy'
	__space-exploration__/scripts/util.lua:892: in function 'safe_destroy'
	__space-exploration__/scripts/spaceship-clone.lua:554: in function 'clone'
	__space-exploration__/scripts/spaceship.lua:831: in function 'land_at_position'
	__space-exploration__/scripts/spaceship-gui.lua:889: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by InappropriatePenguin** [comment]
If you look at the stack trace, the code that crashed is in the mod “Filter combinator”, not SE. You should report this to that mod’s developer.

In the mean time, you can likely avoid this crash by removing all filter combinators from your spaceships.
