### ISSUE TITLE
SE: linked-container.lua grabs any entity of the type "linked-container" which breaks any other mod using that entity type

### ISSUE THREAD

**Issue by Spirevipp** [EarendelDevelopers/factorio-mods#272]
As title says, the linked-container.lua file grabs any placed entity which is using the linked-container entity type, which then breaks any other mod using that entity type.

I currently only know of one mod that uses it, Schall Autolinked Chest.

There is a simple fix for this for Schall Autolinked Chest. Adding the code below to line 22 in linked-container.lua will prevent it from grabbing that mod's chests.
I found this fix in a thread on the discord months ago, so i did not report it again then.

`if entity.name == "Schall-autolinked-chest-1" then return end`

It would be better if SE would only apply its linked-container logic to its own entities.

**Comment by BurninSun** [comment]
Fixed with SE 0.6.109
