### ISSUE TITLE
Error on Blueprint Sandboxes lab force launching a cargo rocket

### ISSUE THREAD

**Issue by structwafel** [EarendelDevelopers/factorio-mods#275]
space-exploration_0.6.98 non-recoverable error

Save:
https://drive.google.com/file/d/1hyn5Do8q8xDSUK4Aqe6B8uRGE6gGfcJG/view?usp=sharing
Log:
[factorio-current (copy).log](https://github.com/EarendelDevelopers/factorio-mods/files/10556895/factorio-current.copy.log)

When loading the map, game seems to be slow, and will result in a non-recoverable error after some seconds.

**Comment by InappropriatePenguin** [comment]
Save file fixed in Discord. Cargo rockets have not been buildable on lab surfaces for a few versions now so no systemic fix is necessary.
