### ISSUE TITLE
Error while running event space-exploration - LuaPlayer API

### ISSUE THREAD

**Issue by joehannes0** [EarendelDevelopers/factorio-mods#279]
When starting a new game from a scenario, this error shows up:

Error while running event space-exploration::on_tick (ID 0)
LuaPlayer API call when LuaPlayer was invalid.
stack traceback:
	[C]: in function '__index'
	__space-exploration__/scripts/remote-view.lua:864: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by InappropriatePenguin** [comment]
Only Freeplay is supported. Other scenarios are not.
