### ISSUE TITLE
Newest version  0.6.100 crashes when launching space capsule for personal transport

### ISSUE THREAD

**Issue by TheKleopiNetwork** [EarendelDevelopers/factorio-mods#280]
Bug introduced in 0.6.100, not present in 0.6.99

The mod Space Exploration (0.6.100) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
Unknown entity name: se-sound-silo-clamps-on
stack traceback:
	[C]: in function 'create_entity'
	__space-exploration__/scripts/capsule.lua:798: in function 'tick_journey_ascend'
	__space-exploration__/scripts/capsule.lua:1065: in function 'tick_journey'
	__space-exploration__/control.lua:1451: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

Thank you :)

**Comment by Wiwiweb** [comment]
Thanks for the report, hotfix just released

**Comment by TheKleopiNetwork** [comment]
can confirm, thank you for the quick fix :)
