### ISSUE TITLE
Can you publish

### ISSUE THREAD

**Issue by EgormrcotPC** [EarendelDevelopers/factorio-mods#282]
Can you publish the your mod and needed other mods for factorio to here?

1. i not can download needed other mods in factorio mods and anywhere in internet
2. it's smarter
Make it pleeeeeese, I will be very grateful to you.

**Comment by EgormrcotPC** [comment]
(mod Space Exploration )

**Comment by Wiwiweb** [comment]
I don't think that'll be happening anytime soon, sorry.
