### ISSUE TITLE
Multi-player downloading Map

### ISSUE THREAD

**Issue by ByteOK** [EarendelDevelopers/factorio-mods#283]
So this is the second game we have started with these MODs loaded. We are also using the newest updates. as of today. 2/18/2023
after about 230 hours we can't join the game with multi player. After downloading the map it will disconnect. We are playing over the local LAN.

Any suggestions would be helpful.
![space exploration](https://user-images.githubusercontent.com/125775420/219906570-646d5046-e623-4eb9-895f-d4489cda9e1e.gif)

**Comment by BurninSun** [comment]
Can you attach your Factorio log file after you try to connect? In windows its located at `%appdata%\factorio\factorio-current.log`. Server log would be the best, but client log would likely be helpful as well.

**Comment by ByteOK** [comment]
client
[factorio-current.log](https://github.com/EarendelDevelopers/factorio-mods/files/10777616/factorio-current.log)

server side
[factorio-current.log](https://github.com/EarendelDevelopers/factorio-mods/files/10777635/factorio-current.log)

**Comment by Wiwiweb** [comment]
```
1549.004 Info ClientMultiplayerManager.cpp:714: TransferTarget threw an exception on stopDownload: CRC mismatch. Expected ec8ddde5, got 114b42ad
1549.004 Error ClientMultiplayerManager.cpp:99: MultiplayerManager failed: "Downloading map from other peers failed. Please try again."
1549.004 Info ClientMultiplayerManager.cpp:610: UpdateTick(4294967295) changing state from(ConnectedDownloadingMap) to(Failed)
```

"CRC mismatch" on map download is weird error that I don't know about.
https://forums.factorio.com/viewtopic.php?t=102783
I don't think network errors are caused by SE. The factorio discord or bug forums would be able to help you out better with this.
