### ISSUE TITLE
An unrecoverable error with mod { Space Exploration Postprocess (Required) (0.6.24) }

### ISSUE THREAD

**Issue by PODF-x** [EarendelDevelopers/factorio-mods#285]
When I start a new game ,it will show that to me. But all necessary mods are downloaded.

![QQ图片20230225002357](https://user-images.githubusercontent.com/69449056/221232109-fe1b753c-4d11-462c-9dc7-90c719a0181d.png)

模组 Space Exploration Postprocess (Required) (0.6.24) 引发了无法恢复的错误。
请向模组作者报告此错误。

Error while running event space-exploration-postprocess::on_init()

═══════════════════════
═══════════════════════

Space Exploration is not installed or active but we could not find any incompatibility or missing dependency.
Make sure that `space-exploration` is checked in your Mods menu, then please report this on the Earendel discord with your list of mods:
{["aai-containers"] = "0.2.11", ["aai-industry"] = "0.5.19", ["aai-signal-transmission"] = "0.4.7", ["alien-biomes"] = "0.6.8", base = "1.1.76", ["bullet-trails"] = "0.6.2", ["combat-mechanics-overhaul"] = "0.6.24", ["equipment-gantry"] = "0.1.5", ["grappling-gun"] = "0.3.3", informatron = "0.3.2", jetpack = "0.3.11", robot_attrition = "0.5.13", ["shield-projector"] = "0.1.6", simhelper = "1.1.4", ["space-exploration-graphics"] = "0.6.14", ["space-exploration-graphics-2"] = "0.6.1", ["space-exploration-graphics-3"] = "0.6.2", ["space-exploration-graphics-4"] = "0.6.2", ["space-exploration-graphics-5"] = "0.6.1", ["space-exploration-menu-simulations"] = "0.6.8", ["space-exploration-postprocess"] = "0.6.24"}[/color][/font]
═══════════════════════
═══════════════════════

stack traceback:
	[C]: in function 'error'
	__space-exploration-postprocess__/control.lua:10: in function <__space-exploration-postprocess__/control.lua:5>

**Comment by BurninSun** [comment]
Is "Space Exploration" enabled on the mods menu? Does it show in red text? If not, can you upload your log file after trying to start a game and getting that error? It is located at `%appdata%\factorio\factorio-current.log`

**Comment by PODF-x** [comment]
因为网络的原因导致 （在space-exploration这个模组页面选择下载，但是却没有成功下载其自身，而软件报告了下载完成而不是缺少文件）重新下载这个模组或者使用代理可以解决

**Comment by PODF-x** [comment]
> Is "Space Exploration" enabled on the mods menu? Does it show in red text? If not, can you upload your log file after trying to start a game and getting that error? It is located at `%appdata%\factorio\factorio-current.log`

thanks for suggestion，this error is caused by network and redownload all mods can repair it.
