### ISSUE TITLE
Meteorite allows rails to be placed underneath + trains can pass through

### ISSUE THREAD

**Issue by OliBolly44** [EarendelDevelopers/factorio-mods#286]
![Capture](https://user-images.githubusercontent.com/127397976/223997124-61586e80-b465-472d-bdca-600174d4dc8f.PNG)
I assumed that they would behave like rocks, this seems like a bug.

**Comment by Wiwiweb** [comment]
We have to have it this way to prevent meteors from destroying buildings without leaving ghosts behind.
