### ISSUE TITLE
Decrease message spam from successful meteor intercept

### ISSUE THREAD

**Issue by AartBluestoke** [EarendelDevelopers/factorio-mods#29]
"An option to only notify for meteors that weren't successfully shot down would be nice. I just found out that one of my outposts had a brownout that it couldn't recover from, and turns out it's been bombarded without protection for a while"

Perhaps is the last incoming meteor attack had more than 1 defence unfired, don't notify?

**Comment by EarendelGames** [comment]
I'm ok with this being an option.

**Comment by PeterRibbit** [comment]
Working on this in feature-minor updates

**Comment by megaicemage** [comment]
@PeterRibbit Are you still working on this?

**Comment by BurninSun** [comment]
Fixed in 0.6.113
