### ISSUE TITLE
Jetpack increase maximum health when enter/leaving jetpack-mode

### ISSUE THREAD

**Issue by Noricum** [EarendelDevelopers/factorio-mods#292]
> Version: 0.3.12
>   Bugfixes:
>     - Fixed jetpack healing you on toggle with mods that grant max health bonuses.

After the last jetpack patch, this change now adds the max health bonus to the player everytime enters/leaves the jetpack mode.

![image](https://user-images.githubusercontent.com/30700381/235186422-bd6c4808-2c26-484f-b26f-6f598ba2e9da.png)

After a couple of uses:
![image](https://user-images.githubusercontent.com/30700381/235187087-62759130-b2b3-4485-975b-15971574035f.png)

Health-Bonus is added by https://mods.factorio.com/mod/RPGsystem

**Comment by Wiwiweb** [comment]
RPG System has some jetpack compatibility code that is causing this increased health values in an attempt to restore character bonus values after jetpack toggle. As of 0.3.13 the jetpack mod correctly preserves all character bonuses so RPG System can remove this.

I filed them a ticket: https://mods.factorio.com/mod/RPGsystem/discussion/6476c26526498f7864cb2cdf
