### ISSUE TITLE
Issue with headless server on windows.

### ISSUE THREAD

**Issue by Leonniar** [EarendelDevelopers/factorio-mods#294]
I am running the server using a .bat file in headless mode, in Windows 10

Whenever I try to launch a headless server I get this error:
```
10.738 Error Util.cpp:83: Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048).

At ROOT.simple-entity.se-gate-fragment-14-a.picture.layers[0].hr_version
Modifications: Space Exploration › Combat Mechanics Overhaul

------------- Error -------------
Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048)
```

I have seen this many times on the internet and the only solution suggested is to set the graphics quality of the server settings to normal.
_server-settings.json_ doesn't have an option to change graphics quality so I have tried: 1) Using the _config.ini_ for the server settings (I have read online _config.ini_ is meant for linux servers but I gave it a shot) 2) Using the _server-settings.json_ for the server settings and 3) adding the `--graphics-quality normal` command line in my .bat file 4) Tried removing the "Combat Mechanics Overhaul" mod in case it was causing the issue.
I tried every possible combination of the above mentioned to get it to work but to no avail.

**Comment by BurninSun** [comment]
Solved in discord, appears to be a problem with the base game. Solution was to load game in single player mode, go into settings -> graphics and change sprite resolution to normal. Then exit out and start the server.
