### ISSUE TITLE
Solar index is inaccurate in universe explorer (Space Exploration 0.3.85)

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#3]
The solar power on surfaces is left unmodified from a previous version unless the surface is regenerated. However, when a surface is regenerated, it appears some surfaces still have an inaccurate solar index.

Solar orbits are accurate.
Planet and moon surfaces are accurate.
Planetary orbits, lunar orbits, and asteroid fields are accurate if they are close enough to the star to generate any solar. Their time if they generate solar is always 0.35, and the time of such surfaces if they're not close enough is some nighttime period (somewhere between 0.45 and 0.55). May need additional clarification.
Asteroid fields have no solar, despite claims of 5% solar. Their time is 0.455.
The anomaly is accurate (has no solar).

Spaceships seem to recalculate solar power in real time accurately enough, but they demonstrate the hard leap in solar time as the solar completely cuts off after one tick of going beyond the threshold.

**Comment by EarendelGames** [comment]
I was not able to test the transition of a spaceship from inside a star system to interstellar space. There may still be a jump... My spaceships need an update.
