### ISSUE TITLE
Compatibility: Pipe Recipes can't be unlocked

### ISSUE THREAD

**Issue by KiwiHawk** [EarendelDevelopers/factorio-mods#303]
Minimum mod list:
- AAI Industry
- Bob's Functions Library mod
- Bob's Logistics mod
- Factorio Library
- Krastorio 2
- Krastorio 2 Assets

The following recipes can't be unlocked:
- `bob-valve`
- `copper-pipe`
- `copper-pipe-to-ground`
- `stone-pipe`
- `stone-pipe-to-ground`

AAI Industries already includes compatibility changes for Bob's Logistics, adding these recipes to `basic-fluid-handling`. If Krastorio 2 is also enabled, these recipes should be added to `kr-basic-fluid-handling`.

Adding the following code to `aai-industry\prototypes\compatibility\krastorio2.lua` fixes the issue:
```lua
    if mods["boblogistics"] then
      data_util.tech_lock_recipes(
        "kr-basic-fluid-handling",
        {
          "bob-valve",
          "copper-pipe",
          "copper-pipe-to-ground",
          "stone-pipe",
          "stone-pipe-to-ground"
        })
    end
```

**Comment by Wiwiweb** [comment]
Sorry this took so long to get to this. You did your investigation well. I'll try and get a release for this soon.
