### ISSUE TITLE
Arcolink storage code interacts poorly with mods that use linked-container

### ISSUE THREAD

**Issue by mpcomplete** [EarendelDevelopers/factorio-mods#304]
I wrote a mod called Unichest, which adds a new entity of type linked-container. There is code in SE's scripts/linked-container.lua line 21 that checks if an entity.type is "linked-container", and if so, it assumes it is an arcolink storage and manipulates its link_id. I think this instead should check if the entity name is "se-linked-container", to avoid affecting other entities of that type. Similarly with other code in SE that affects arcolink storages.

The interaction of this bug with my mod is explained in the bug report here: https://mods.factorio.com/mod/Unichest/discussion/649f9eb361c0c94711d3d3f7#post-2

**Comment by BurninSun** [comment]
The general issue with SE modifying linked chests has been fixed for next release.

**Comment by mpcomplete** [comment]
Thank you!

**Comment by BurninSun** [comment]
General fix went live with 0.6.109 which should fix this, though this mod itself was not tested.
