### ISSUE TITLE
Custom Modules breaks Space Exploration

### ISSUE THREAD

**Issue by Shiverous** [EarendelDevelopers/factorio-mods#311]
The **Custom modules** mod removes the basic vanilla module technologies `(e.g. "productivity-module")` thus breaking **Space Exploration** via its "technology.lua" depending on those technologies, in the Phase-3 folder inside the prototypes folder.

I'd contact the owner of Custom modules but it seems abandoned and all other mods work fine except SE.

I suggest disabling or changing those prerequisites when SE detects Custom Modules is installed? Have a nice day.

**Comment by Wiwiweb** [comment]
Sorry, we only guarantee full compatibility with Krastorio 2, though we sometimes go out of our way to add compatibility code for big or popular mods.

If that mod is abandoned your best bet is to make your own fork to add SE compatibility.
