### ISSUE TITLE
Crash to black screen

### ISSUE THREAD

**Issue by Sludger1** [EarendelDevelopers/factorio-mods#317]
I'm new to SE and I've been having an issue where the game will crash to black screen while interacting with the cargo rocket silo. It usually occurs while clicking on it, but it can also crash while the character is entering it, and recently it has crashed while already interacting in the menu.

Attached is my current log.

[factorio-current.log](https://github.com/EarendelDevelopers/factorio-mods/files/12476960/factorio-current.log)

**Comment by Wiwiweb** [comment]
There's nothing weird in your log unfortunately.
Try reporting it to the Factorio developers since this is a hard Factorio crash.
https://forums.factorio.com/viewforum.php?f=7
