### ISSUE TITLE
AAI Signal Transmission 0.4.8 Migration Error

### ISSUE THREAD

**Issue by osimon8** [EarendelDevelopers/factorio-mods#318]
I had a scenario with the SpaceEx suite of mods that I was using to develop some circuit contraptions, which I haven't touched in a while. It was using some old versions of mods, namely AAI Signal Transmission 0.4.7. After updating to 0.4.8 however, when I try to load the scenario I am met with the following unrecoverable error:

![signals_error](https://github.com/EarendelDevelopers/factorio-mods/assets/14896850/5c1d0219-14da-4026-bcf9-4fbc5cf51857)

Happy to provide more information or the specific world data if that's helpul.

**Comment by Wiwiweb** [comment]
Thanks for the report and sorry for the late answer. This will be fixed in a soon-to-be-released version.
