### ISSUE TITLE
Space capsule cargo items cleared

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#32]
When you launch a space capsule with power armor in the space capsule's cargo, the power armor loses its contents (personal roboports, batteries, etc.).

Problem is transfer as simple item stacks, it needs to use the newer swap inventories function.

**Comment by AvengerStar** [comment]
I reckon I should handle this alongside the other space capsule ticket.

**Comment by Derunih** [comment]
Armour inventories have been fixed, navigation still being worked on in the same branch
