### ISSUE TITLE
[AAI Loaders] Entity Order

### ISSUE THREAD

**Issue by KiwiHawk** [EarendelDevelopers/factorio-mods#327]
**Request:** Please don't set `order` property on Loader entities. Delete loaders.lua:107

If `order` is not specified on an entity and that entity has an object to place it, the entity's order is set to `"z-"..item.order`. I asked Bilka why this functionality exists. They didn't know but requested that I create a documentation request.
https://forums.factorio.com/viewtopic.php?f=233&t=109705

Entity order is used by helper mods such as Helmod (pictured below) as well as the the vanilla GUI to select an upgrade.

As the loader entities _do_ have an order string set, and it doesn't include the "z-" prefix, they are sorting differently to their related items. They will always be sorted first as other entity's order begins with "z-".

In game, I can see the order of the yellow tier loader is `"d[loader]-a01[aai-loader]"`. If I overwrite the entity's order, setting it to `nil`, then in game I can see it's order will be `"z-d[loader]-a01[aai-loader]"`.

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/59639/bc9c6b8c-8c5f-4a1e-95bf-11197001d175)

**Background:** I've taken over maintenance of Bob's Mods. I'm working on adding AAI Loader to support to Bob's Logistics mod. Screenshots are from my work in progress.

After setting `entity.order = nil`, it looks like this:
![image](https://github.com/EarendelDevelopers/factorio-mods/assets/59639/56db484a-997d-467f-99d4-866b3718141c)

https://github.com/modded-factorio/bobsmods/issues/109

**Comment by Wiwiweb** [comment]
That makes sense to me, thanks.
