### ISSUE TITLE
[AAI Loaders] Ghost belt snapping

### ISSUE THREAD

**Issue by KiwiHawk** [EarendelDevelopers/factorio-mods#328]
If a blueprint contains a belt connected to a loader, the belt will snap to the loader in 3 out of 4 orientations.

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/59639/9e45f99f-2341-40e0-9b22-14fef9e13d23)

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/59639/bca04573-e538-4355-bf96-bec49e842030)

**Comment by Wiwiweb** [comment]
Took me a moment to understand what you meant. It's the green ghost outline before placing that has the belts a bit weird looking, but only in 1 out of 4 directions.

That is weird indeed but vanilla loaders show the same behaviour so looks like it's just a weird Factorio quirk.

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/4723472/41e437b7-5859-4901-b287-5e8f3a270589)

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/4723472/7d081a8f-b1e9-4361-916e-6b722925fb29)

**Comment by KiwiHawk** [comment]
Thanks for looking at this. I'll report it as a base game bug!

https://forums.factorio.com/viewtopic.php?f=7&t=109999

**Comment by KiwiHawk** [comment]
Fixed in Factorio 1.1.100
