### ISSUE TITLE
[Space Exploration] Alternative holmium based processing unit recipe for Krastorio 2

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#33]
The planned replacement recipe is to be:
- 3 Advanced Circuits
- 2 Rare Metals
- 4 Sulfuric Acid
- 8 Holmium Cable

to make 2 Processing Units in 12 seconds.

This recipe (as well as its unlock in holmium cable technology and productivity permissions) should be placed in postprocess, within the Krastorio 2 compatibility file.

**Comment by EarendelGames** [comment]
ok, are you adding this?

**Comment by AvengerStar** [comment]
I will, I mainly put it in a ticket to set it aside for the time being.

**Comment by InappropriatePenguin** [comment]
This was added in 0.3.113.
