### ISSUE TITLE
Failed interact with interface and setup items

### ISSUE THREAD

**Issue by Klutae** [EarendelDevelopers/factorio-mods#330]
After 300 hours of play, the game periodically began to block interaction with items, properties, and hotkeys. Loading a save now prevents you from interacting with anything at all.  Example https://disk.yandex.ru/d/4JjoCnAKzzHS9g

**Comment by Wiwiweb** [comment]
This is caused by the Kruise Kontrol mod, I would report that to them.
You can ctrl alt click a bunch of things and that fixes it.
