### ISSUE TITLE
space trains skipping stops and cycling through space elevator

### ISSUE THREAD

**Issue by Charge12345** [EarendelDevelopers/factorio-mods#335]
whenever one of my space trains goes through the elevator it skips its intended stop and just goes back to the elevator. I don't have any skip stations mods and this is something that started recently. I know it isn't the design I am using because it was working before and I haven't added or changed anything. The result is the trains just running through their battery packs and becoming stuck on Nauvis without power. https://clipchamp.com/watch/3hkIEfXJKFK

**Comment by Charge12345** [comment]
https://clipchamp.com/watch/3hkIEfXJKFK

**Comment by Wiwiweb** [comment]
Which SE version are you using?

**Comment by Charge12345** [comment]
It was a conflict with a train skip mod that got enabled after I fixed a
corrupted save file thanks
