### ISSUE TITLE
Pyramid Issue

### ISSUE THREAD

**Issue by IdeoPraxist1** [EarendelDevelopers/factorio-mods#337]
While inside a pyramid, the game crashed. This is the error log:

Error while running event space-exploration::on_player_changed_position (ID 86)
__space-exploration__/control.lua:775: attempt to index field 'character' (a nil value)
stack traceback:
	__space-exploration__/control.lua:775: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>
	[C]: in function 'teleport'
	__space-exploration__/control.lua:281: in function 'teleport_character_to_surface'
	__space-exploration__/control.lua:798: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>
stack traceback:
	[C]: in function 'teleport'
	__space-exploration__/control.lua:281: in function 'teleport_character_to_surface'
	__space-exploration__/control.lua:798: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by Wiwiweb** [comment]
Are you on the latest SE version? The line numbers don't match the current code.
Can you reproduce this and if so does it still happen on the latest version?

**Comment by IdeoPraxist1** [comment]
Hi William,

I re-patched the game to the latest version and the problem had been fixed.

Thanks for making an excellent mod for Factorio.

IdeoPraxist
