### ISSUE TITLE
Jetpack compatibility with Scooty's Armor Swap - graphics do not update along with player color changes

### ISSUE THREAD

**Issue by scotthmccoy** [EarendelDevelopers/factorio-mods#338]
My own mod, [Scooty's Armor Swap](https://mods.factorio.com/mod/scootys-armor-swap), adds a hotkey which cycles through armors in the inventory and updates the player's color to whatever it was when the armor was last worn, effectively allowing armors to be "dyed".  Sadly, player color changes do not seem to affect the jetpack.

**Expected:**
Changing player color while using jetpack will change the color of the jetpack sprites

**Observed:**
Jetpack sprite color changes do not take effect until the player lands

**Proposed Fix:**
Insert the following on line 71 of `jetpack-graphics-sound.lua`:

```
    rendering.set_color(jetpack.animation_mask, jetpack.character.player and jetpack.character.player.color or jetpack.character.color)
```

I've tested the fix pretty thoroughly and it doesn't seem to affect UPS.

**Comment by Quezler** [comment]
alternatively, in your own mod it should be possible to do: (in an event listener, so it doesn't run every tick)
```lua
local jetpack = remote.call("jetpack", "get_jetpack_for_character", {character=player.character})
rendering.set_color(jetpack.animation_mask, jetpack.character.player and jetpack.character.player.color or jetpack.character.color)
```

**Comment by scotthmccoy** [comment]
Oh dang, I didn't realize that mods can talk to each other like that. That fix is working perfectly, thank you!
