### ISSUE TITLE
statuslight of big mining drills with modules

### ISSUE THREAD

**Issue by herztequila** [EarendelDevelopers/factorio-mods#339]
hey,
if you put modules in the big mining drills in space exploration and the ALT-mode ist activated the modules hide the statuslight of the drills if the drill output points downside.
![drills](https://github.com/EarendelDevelopers/factorio-mods/assets/162873086/ee15ece6-6617-4d06-a650-7bdbe77a1ca5)
maybe you can rearrange the modules tat the light is visible?
best wishes

ps: you're doing great work in space exploration and factorio, i really like the game and the mod! :)

**Comment by Wiwiweb** [comment]
This is an issue but it would be difficult to fix unfortunately.
As a workaround you can use https://mods.factorio.com/mod/BottleneckLite
