### ISSUE TITLE
[Space Exploration] Weapons delivery cannon auto-targeting setting akin to auto-glaive

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#34]

**Comment by EarendelGames** [comment]
Target selection will be a random enemy entity on the surface. Look for non-unit targets first. The effect will be a bit like random orbital bombardment, but will actually hit enemy structures.

**Comment by daviscook477** [comment]
is this different from the auto target option available on the weapons delivery cannon now?
or was this issue just never closed?

**Comment by AvengerStar** [comment]
This issue was never closed. Unless you'd prefer to reuse the ticket for any issues associated with it, or missing features related to it, it will be closed as the feature has been implemented.
