### ISSUE TITLE
[KE2] Steam recipes in electric boiler need update

### ISSUE THREAD

**Issue by sergv** [EarendelDevelopers/factorio-mods#340]
Recent Space Exploration introduced compatibility fix for Krastorio 2 that lowers heat capacity of steam from `0.5KJ` to `0.3KJ`. But the eneregy requirements of electric boiler recipes are computed with Krastorio's `0.5KJ` capacity thus leading to mismatch.

Use vanilla's `0.2KJ` as a reference: 100 units of 500 degree steam takes 2.15 seconds to produce. With `0.3KJ` capacity it should be +50%, yet in the fresh install of Space Exploration and Krastorio 2 (done just now) the recipe takes 5.38 seconds, because it was computed against `0.5KJ` capacity (ratios 5/2 match up).

While we're at it it would be cool to add 415 degree steam when Krastorio 2 is around since 500-degree one has no use (or at least is not used that much as in vanilla SE) - turbines consume 415 degree steam.

**Comment by Wiwiweb** [comment]
@DarkStarBuster

**Comment by Trenjeska** [comment]
Seconded.
K2SE now indeed has an Electric Boiler / steam consumer  mismatch

**Comment by Wiwiweb** [comment]
This should be fixed in the next update, SE 0.6.131
