### ISSUE TITLE
Problem with Bob's Logistics mod

### ISSUE THREAD

**Issue by grekoslav** [EarendelDevelopers/factorio-mods#344]
После обновления мода иследование космоса, начало выдвать ошибку, ошибка решается удалением Bob's Logistics mod. Мне бы очень хотелось продолжить использовать Bob's Logistics mod. Но мне не удается устранить проблему другим образом. Может вы сможете помочь. Спасибо. 

Ошибка: https://ibb.co/3mVCQzG

**Comment by grekoslav** [comment]
After updating the space exploration mod, it started giving an error, the error is solved by removing Bob's Logistics mod. I would really like to continue using Bob's Logistics mod. But I can't fix the problem any other way. Maybe you can help. Thank you.

Error: https://ibb.co/3mVCQzG

**Comment by BurninSun** [comment]
Fixed with 0.6.132.
