### ISSUE TITLE
Combat Mechanics Overhaul touches my hidden accumulators

### ISSUE THREAD

**Issue by James-Fire** [EarendelDevelopers/factorio-mods#345]
It changes their icon, and sets their upgrade to another accumulator without care for if that upgrade is even valid.

https://cdn.discordapp.com/attachments/888589621078929458/1245915572319948971/image.png?ex=665a7ccc&is=66592b4c&hm=3ed2301b2678b5f6811f20932cbac054233aeb4f703cc134547e6e42701143aa&

A) You shouldn't be setting entities to upgrade to other entities without checking that it's a valid upgrade

B) Why are you even touching upgrades *or* icons on accumulators in CMO in the first place?

I have added a line to my mod to undo the upgrade for now, so it still works, but you need to fix this on your end.

My accumulator as it should be:
https://cdn.discordapp.com/attachments/888589621078929458/1245914832222552237/image.png?ex=665a7c1b&is=66592a9b&hm=e1ce7532d446dd519636c806bd398f4b62b49238bd54749ff155de67b9484c56&

My accumulator after you touch it:
https://cdn.discordapp.com/attachments/888589621078929458/1245914270084890695/image.png?ex=665a7b95&is=66592a15&hm=b6f70fa7bb3a613c11b7e6be2bc4f85cd2eeca063d884a7c2395755c0c241270&

**Comment by heinwessels** [comment]
The images you linked isn't displaying, so it's hard to see the problem you are having. You can paste images straight into the description, or comments, like this. Seeing the images will help diagnose your issue :)
![image](https://github.com/EarendelDevelopers/factorio-mods/assets/39875036/9b9a3da2-e54f-48c8-bdf4-6b60da70e376)

I don't see anything related to [next_upgrade](https://lua-api.factorio.com/latest/prototypes/EntityPrototype.html#next_upgrade) in CMO's code though

**Comment by James-Fire** [comment]
The images in order

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/41241412/8112a90f-8f31-49bc-a018-9fd309ac8f62)

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/41241412/7ce94430-d37f-499d-8235-f42ef241a80e)

![image](https://github.com/EarendelDevelopers/factorio-mods/assets/41241412/11f9730e-d0a9-453e-af3c-192123512eff)

Yeah, I looked in CMO as well and couldn't find something that should do it, but my entity is only edited by it.

**Comment by BurninSun** [comment]
Can you provide the line of code that needs to go into your mod to cause this? With just CMO and your mod loaded as-is, everything looks normal.

**Comment by James-Fire** [comment]
Yes, as I said I added a line to undo the upgrade, which allows it to load.

https://github.com/James-Fire/James-Train-Mod/blob/40965ff659f944914ebac5a750498605c15fd0d7/data-final-fixes.lua#L28

This line fixes the loading issue by removing the upgrade in the accumulator. I did not fix the icon or naming.

My accumulator is copied from the vanilla accumulator, with this stuff set after copying. I'm not sure how this happens, since CMO doesn't appear to actually do it, but it's also the only one that touches it

**Comment by BurninSun** [comment]
Loading up CMO and James' Train Mod, in the startup settings I enable everything in yours, and the only thing that CMO changes with your prototype is adding: 
```
  trigger_target_mask = {
    "ground-static"
  },
```
Here is the entity tooltip: 
![image](https://github.com/EarendelDevelopers/factorio-mods/assets/12116957/c638bf54-e32a-4099-bb75-95c776a0b4f6)

and the `next_upgrade` is `<empty>`
CMO itself never sets `next_upgrade` anywhere in its code.

Not sure what is going on, but its more than just CMO modifying things.

**Comment by James-Fire** [comment]
No idea on the icon or description either?

**Comment by BurninSun** [comment]
Its some other mod doing it, just not showing in the prototype history for some reason. Can try disabling mods until it is corrected.

**Comment by James-Fire** [comment]
Well I have a guess who's doing it then...
