### ISSUE TITLE
Crash Error ID 24 

### ISSUE THREAD

**Issue by Madullier** [EarendelDevelopers/factorio-mods#347]
got an crash just now from the meteor script
just updated to latest (0.6.136)

Error while running event space-exploration::on_trigger_created_entity (ID 24)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__space-exploration__/scripts/meteor.lua:1411: in function 'callback'
	__space-exploration__/scripts/event.lua:20: in function <__space-exploration__/scripts/event.lua:18>

**Comment by BurninSun** [comment]
0.6.137 is released which should fix this.

**Comment by Madullier** [comment]
perfect thanks 
its fixed
