### ISSUE TITLE
EarlyExtensions and AAI Programmable Vehicles Mod Bug

### ISSUE THREAD

**Issue by Cooltank10** [EarendelDevelopers/factorio-mods#348]
Hi, I'll try to keep this short as your probably a busy person. So I tried using those 2 mods together but I got a error that basically said "EarlyExtensions doesn't recognize the recipe (??) for the AAI Programmable Vehicles mod's Unit Controller. I think the EarlyExtensions mod is built to check recipes and techs to see if there should be a new tech requirement (an earlier tech to elongate the early game sort of like a burner stage). Currently it cannot check the recipe of the controller for some reason as I cannot access the source code for AAI Programmable Vehicles mod. I would like to use EarlyExtensions as it fits nicely into the balance of my own modpack I'm curating, but I also want to use AAI Programmable Vehicles mod as I think its a very cool mod. Is there a way to either patch that bug out in particular and/or let me see the code of AAI Programmable Vehicles mod to assist in fixing it? I would appreciate it a lot, thanks!

Note: From looking at the source code for EarlyExtensions, the bug seems to be that the controller is not in a 'recipe category'. I don't know much about coding in lua or factorio for that matter, so I'm not sure what a 'recipe category' is. (might be similar to the character crafting screen categories..?) I can give you some snippets of the other mods code that error'd if you would like.

![Factorio_EarlyExtensions+AAIProgrammableVehicles_Error](https://github.com/EarendelDevelopers/factorio-mods/assets/129795626/69525d54-ab23-4e58-947e-1753f7bc7e3f)

**Comment by Wiwiweb** [comment]
The "unit-remote-controller" is a "selection-tool" and DragonIndustries doesn't recognize this type of item. It is a bug on their side.
https://github.com/ReikaKalseki/DragonIndustries/blob/master/items.lua#L96-L114

To be honest AAI Programmable Vehicles is not maintained much anymore either, it might not be ported to Factorio 2.0, or at least not for a while.
