### ISSUE TITLE
[AAI loaders] graphical only or no lubricant mod still have script running

### ISSUE THREAD

**Issue by Stargateur** [EarendelDevelopers/factorio-mods#349]
It could be nice to have zero script running when loaders are set to graphical only or no lubricant mode. This should be as simple as a if in the control.lua code.

**Comment by Wiwiweb** [comment]
Even without lubricant mode there are scripts to attempt auto-snapping of loaders. Those scripts don't cause any ongoing UPS cost though, they only run on entity placement of aai loaders.

**Comment by Stargateur** [comment]
This is false since not placing any loader still pop aai-loader as mod running script in debug mod.

**Comment by Wiwiweb** [comment]
What do you mean?

**Comment by Stargateur** [comment]
> What do you mean?

what I write, if I do nothing, then aai-loader should do nothing right ? and yet it was showed in time usage. Anyway, I still wish we have a separate mod for graphics, this would also simplify a lot code of aai loader if you decide to drop graphic only mode later. Other loader that use graphics only doesn't use script code of aai loader.

Having a pure mod with only graphics would be better overall.
