### ISSUE TITLE
Suggestion: beacon overload of an entity should be an alerting action

### ISSUE THREAD

**Issue by AartBluestoke** [EarendelDevelopers/factorio-mods#35]
beacon overload of an entity should be an alerting action, there are several questions about "why isn't my assembler working".
if there are people who are asking in the discord, there are probably many more having issues ingame.

Machines 100% offline due to overload are more important than destruction by meteor strike, as repair bots will probably fix the latter, but the overload won't fix itself.

**Comment by EarendelGames** [comment]
Agreed.

**Comment by InappropriatePenguin** [comment]
So I added `add_custom_alert` and `remove_alert` calls to the `Beacon.validate_entity` function where appropriate and they seem to work as expected.

One persistent issue is that the alert that is generated is fairly short-lived and disappears after a few seconds, even without user interaction. It also does not seem to be possible to set the timeout period for custom alerts.

One possibility would be to have a function that regularly (say, every couple of minutes) checks `global.beacon_overloaded_entities` and generates alerts if needed. That may be more overhead than this is worth—I'm not sure.

**Comment by InappropriatePenguin** [comment]
Feature has been added.
