### ISSUE TITLE
Crash with on_tick event in scenario editor

### ISSUE THREAD

**Issue by ondrejkajinek** [EarendelDevelopers/factorio-mods#351]
After full upgrade (F 1.1.110, SE, 0.6.138), starting ticks in Scenario Editor causes the following error:

```
Exception at tick 48567: The mod Space Exploration (0.6.138) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_tick (ID 0)
__space-exploration__/scripts/spaceship-obstacles.lua:418: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        __space-exploration__/scripts/spaceship-obstacles.lua:418: in function 'tick_projectile_speeds'
        __space-exploration__/scripts/spaceship.lua:2312: in function 'callback'
        __space-exploration__/scripts/event.lua:20: in function <__space-exploration__/scripts/event.lua:18>
```

List of active mods enclosed.
[modlist.txt](https://github.com/user-attachments/files/16798907/modlist.txt)

When playing the scenario as a single player game, it crashes, too.

It seems `on_init` wasn't run when loading the scenario - after I hotfixed the issue with `or {}`, delivery cannon payloads crashed next (also global variable set during `on_init`).

**Comment by ondrejkajinek** [comment]
I think this is related to migrations. I updated SE from 0.6.130 to 0.6.138, then my scenario save started crashing. Creating a new scenario (with +- the same content, I'm using it for blueprint planning) works fine.

**Comment by Wiwiweb** [comment]
![image](https://github.com/user-attachments/assets/96e202fb-593e-4187-9695-007927f339ac)
Nothing we can do unfortunately, migrations act weird when applied to scenarios. In recent versions of SE, starting the mod in a scenario will show a warning message. Maybe this will be different in 2.0
