### ISSUE TITLE
[Space Exploration] Rockets without a targeted landing pad should only have a manual launch option

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#36]
If a landing pad is not present on the destination zone:
**A rocket has crash landed without a targeted landing pad at [gps tag]. Consider adding a landing pad at the destination.**

If a landing pad is already present on the destination zone:
**A rocket has crash landed without a targeted landing pad at [gps tag]. Consider targeting a landing pad at the destination from the launchpad interface.**

This console readout is meant to only fire when a rocket without a targeted landing pad does not have a player or spidertron on board. The actual language of "crashing" may be changed depending on interpretation.

**Comment by Alpha-Prime-01** [comment]
I am AlphaPrime, Creator of the Coal Belt; and I approve this message.

**Comment by AvengerStar** [comment]
A better suggestion was made in the Discord by user RedAlert, stating to only have a manual launch option for rockets that do not have a landing pad at their destination. This is simpler, and avoids having rockets mistakenly launched in this manner in the first place.

**Comment by BurninSun** [comment]
Fixed in 0.6.114
