### ISSUE TITLE
Warden: Description of electroshock pulse ammo is not showing

### ISSUE THREAD

**Issue by nibasya** [EarendelDevelopers/factorio-mods#37]
In aai-vehicles-warden_0.4.2, a description for electroshock pulse ammo is not shown in the game though it is defined in strings.cfg.
![image](https://user-images.githubusercontent.com/15785731/94924569-bc26ec00-04f8-11eb-84c3-41be0a251add.png)
It is defined as following right now.

electroshock-pulse=An electrical area pulse designed to stun and immobilise biological enemies. Fired from the Warden's Electro Bolter turret.

Probably, the name of the definition lacks "-ammo"; It might be "electroshock-pulse-ammo" instead of "electroshock-pulse".

**Comment by Derunih** [comment]
Confirmed now displays correctly
