### ISSUE TITLE
Miner: technology desc. is not shown correctly for Miner MK. 2-5

### ISSUE THREAD

**Issue by nibasya** [EarendelDevelopers/factorio-mods#38]
In aai-vehicles-miner_0.5.9, technology desc. of Miner MK. 2-5 is not shown correctly.

In strings.cfg, Miner's technology desc. are defined as following:
`vehicle-miner=An excavation and mining vehicle that can mine solid resources such as coal, stone, ores, and harvests trees.`
`vehicle-miner-mk2=Faster mining, faster driving, higher capacity, better efficiency, less pollution.`
`vehicle-miner-mk3=Faster mining, faster driving, higher capacity, better efficiency, less pollution.`
`vehicle-miner-mk4=Faster mining, faster driving, higher capacity, better efficiency, less pollution.`
`vehicle-miner-mk5=Faster mining, faster driving, higher capacity, better efficiency, less pollution.`

but, their desc. in the game is that of MK. 1.
example: desc. of MK.2.
![image](https://user-images.githubusercontent.com/15785731/94925993-1163fd00-04fb-11eb-846e-194b54f06f30.png)

**Comment by Derunih** [comment]
Confirmed fixed in current version
