### ISSUE TITLE
Speed Bonus from RPG System is overwritten until respawn when using jetpack (Jetpack 0.1.19)

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#4]
Mod in question: https://mods.factorio.com/mod/RPGsystem

There may be other values that are overwritten, so just in case a pass should be made such that every value from this mod works properly.

**Comment by Wiwiweb** [comment]
Confirmed fixed.

Specifically the RPG mod modifies character.character_running_speed_modifier which jetpack no longer touches.

**Comment by tonylukasavage** [comment]
@Wiwiweb  Factorio 1.1.109

I'm using jetpack (0.3.14) and I'm running into a similar issue with RPG System (1.3.5). Every time I enable the jetpack, I lose all my stat increases from RPG System. It can be worked around by resetting stats and re-applying them, but that obviously sucks.
