### ISSUE TITLE
Biology catalogue 2,3,4 are too expensive for insight

### ISSUE THREAD

**Issue by pepperbox2020** [EarendelDevelopers/factorio-mods#41]
after adjustiment of ratio based on insight returns, bio2 cat takes 2 times of vita and vulc than bio1 cat does, and bio3 and 4 cat takes 7 times of vita and 100 times of vulc than bio 1 cat

**Comment by pepperbox2020** [comment]
![image](https://user-images.githubusercontent.com/72322226/95003000-e8cc2800-060c-11eb-9e4d-2f8385c54a79.png)
![image](https://user-images.githubusercontent.com/72322226/95003006-000b1580-060d-11eb-864f-9d98ea918038.png)
![image](https://user-images.githubusercontent.com/72322226/95017107-cf1cf600-0689-11eb-8b38-5c4d1c9e1af6.png)
bio 4 in the first pnj was incorrect, above and below are the up to date one
![image](https://user-images.githubusercontent.com/72322226/95017124-012e5800-068a-11eb-853e-d0f9e054ad7c.png)

**Comment by AartBluestoke** [comment]
@pepperbox2020 could you attach the helmod production line for those figures?

**Comment by pepperbox2020** [comment]
[bio1.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5323279/bio1.txt)
[bio2.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5323280/bio2.txt)
[bio3.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5323281/bio3.txt)
[bio4.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5323282/bio4.txt)
@AartBluestoke not sure if it will keep the same as in my save, it might need some manual adjustment to work

**Comment by AartBluestoke** [comment]
the vita costs are *much* lower than you suggest - look at the output - the via goes to the bio goop outputs which are inputs also.
(only relevent for lvl 4 - lvl 2/3 don't have those as outputs)

<edit - removed comment about spice, as it's the final stage that consumes most of the vulcanite>

perhaps the issue is the requirement of 1:1 ratio with vulcanite at the high level, forcing the 1:1 ratio with the lower level via reagent

**Comment by AartBluestoke** [comment]
also, the contaminated cosmic water is 1% biosludge, and contaminated scrap is 1/20 biosludge - if you reprocess the water and scrap outputs you get less bio input.

ie, the lvl 2 recipe also produces ~36 sludge, offsetting the need for ~5 nuggets each (or about 180/2, or 90 of the 392 via)

For these testing scenarios, could we run with 'bio from fish' or something, so that we can separate out the demand for biosludge from actual via demand from the reciepes (eg:acid requirements)

**Comment by pepperbox2020** [comment]
@AartBluestoke actually after my calculation I found that bioloop using biomass is the cheapest option for vita, and using this method the outputing bio sludge from bio4 only worth less than 1% of the vita input, and this is also the reason I negelite the biosluge from cosmic water.

**Comment by pepperbox2020** [comment]
maybe not less than 1% but should be less than 5% ,don't remember

**Comment by pepperbox2020** [comment]
so they are negligible

**Comment by AvengerStar** [comment]
The insight returns have been adjusted as of Space Exploration 0.4.32. Do the new values adjust the balance sufficiently?

**Comment by AvengerStar** [comment]
The insights have been boosted. I'm not entirely sure from the response I did get in discord whether or not this is satisfactory, but I assume it is no longer an issue at this point.

**Comment by pepperbox2020** [comment]
Actually, I'm not sure if the issue are solved as bio 3 and 4 still need about 5x vita and 100x vulcanite blocks compare to bio 1

**Comment by pepperbox2020** [comment]
bio 2 is much better and I'd say very competitive now as it only need silghtly more vita,vulc and chemical gel and require much smaller amount of everything else

**Comment by pepperbox2020** [comment]
However bio 3 is just not competitive at all. It needs about 4x vita and 100x vulc compare to bio 2, and requires most thermofluid among 4 levels, also datacard usage is pretty much same as bio2. Also the increased complexity as significant biomass is needed. All these but it has only negligible decrease in some other resource cost such as glass and chemical gel (well fairly talking it does not require lubricant anymore unlike to bio 1 and 2), while have a little increase in other ingradients cost. Form the reasons above I'd say that bio3 catalogue is the worse one among the 4.

**Comment by pepperbox2020** [comment]
[bio1.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5450062/bio1.txt)
[bio2.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5450064/bio2.txt)
[bio3.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5450065/bio3.txt)
[bio4.txt](https://github.com/EarendelDevelopers/factorio-mods/files/5450067/bio4.txt)
Heres the helmode string

**Comment by pepperbox2020** [comment]
<img width="663" alt="bio1" src="https://user-images.githubusercontent.com/72322226/97401457-d1dad600-192b-11eb-8294-63d355d6ea9f.png">
<img width="701" alt="bio2" src="https://user-images.githubusercontent.com/72322226/97401465-d43d3000-192b-11eb-8b0a-e35f853e6245.PNG">
<img width="661" alt="bio3" src="https://user-images.githubusercontent.com/72322226/97401468-d4d5c680-192b-11eb-8d75-b53a9940a883.PNG">
<img width="663" alt="bio4 1" src="https://user-images.githubusercontent.com/72322226/97401471-d56e5d00-192b-11eb-8163-207dddb6436f.PNG">
<img width="663" alt="bio4 2" src="https://user-images.githubusercontent.com/72322226/97401473-d69f8a00-192b-11eb-9f19-e27991a532e6.PNG">

**Comment by pepperbox2020** [comment]
Bio 4 can be attractive as it needs least thermofluid and datacard, and itself is a bio sludge positive process. The increased vita vulc production might not be a pain as raw materials can be processed before sending to space (therefore low logistics tax), and the raw resources are abudant.
HoweverI'm not sure if it is worth to do as it has to combine with bio 3 catalogue (which is the most expensive one among 4)

**Comment by AvengerStar** [comment]
I requested your response both on here and on discord. From what you gave me, you seemed to imply you didn't have any issues with what was given.

Have a solid plan that wouldn't be too much effort to try and balance with itself, without possibly throwing other sciences out of balance. Until then, the issue will remain closed.
