### ISSUE TITLE
Spaceship Clamps in blueprints or copy/paste can be off the rail grid.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#48]
The item you place for a spaceship clamp is a section of rail. The image is different based on cardinal vs diagonal direction, and that is used to swap in the combinator-based entity when the entity is palced.

In a blueprint it only has the combinator entitty. The task is that when a blueprint is created (or temp blueprint from cut/copy) the blueprint should be edited by script to replace the combinator version with the rail version of the clamp with the appropriatie orientation. 

The hard part here is probably going to be detecting the copy/cut blueprint creation.

**Comment by wladekb** [comment]
Can this be simplified by changing the inner mechanism? Let the original rail be still placed so that it ends up in blueprint normally and employs the vanilla restrictions for placing rails. It would work in a very similar way as the other existing SE "composite" entities. @EarendelGames your call?

**Comment by Derunih** [comment]
Confirmed fixed in the current version, including blueprinting only half the clamp entities. Were there any other components to this bug?

**Comment by BurninSun** [comment]
Fixed in 0.5.102
