### ISSUE TITLE
Tesla gun UPS

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#56]
Try surface.find_enemy before looking for other entities.

**Comment by BurninSun** [comment]
@EarendelGames 
I'm doing some optimizations on tesla guns when I ran across this post. Currently, the target selection doesn't discriminate between enemy or neutral (trees/rocks/etc). Using find_enemy first would prioritize enemy units. Is that the intent?

**Comment by BurninSun** [comment]
Fixed in 0.6.95
