### ISSUE TITLE
[Space Exploration] Only one player in multiplayer gets exploration journal updates

### ISSUE THREAD

**Issue by bonesbro** [EarendelDevelopers/factorio-mods#59]
When playing multiplayer, only one player receives new exploration journal updates when achieving something new.  It would be nice if every player currently in the game could get those updates.  We have been working around the issue by sharing screenshots but it would be more convenient if we all got them in our journal.

Two specific examples:
1. I was sitting on Nauvis.  My brother went into a ruin on another planet for the first time.  He got a journal entry ("cartouche").  I did not.
2. I was sitting on Nauvis.  My brother flew out to an anomaly and saw two broken things.  He got a bunch of journal updates.  I got nothing.

**Comment by EarendelGames** [comment]
Those entries are person specific. You'll get those entries if you go there later.
