### ISSUE TITLE
[Space Exploration] 0.5.21 single  Error while running event space-exploration::on_player_changed_position (ID 82)

### ISSUE THREAD

**Issue by jackpassero** [EarendelDevelopers/factorio-mods#60]
Crash when enter a pyramid

```
3798.898 Error MainLoop.cpp:1281: Exception at tick 122715096: Мод Исследование космоса (0.5.21) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event space-exploration::on_player_changed_position (ID 82)
__space-exploration__/control.lua:600: attempt to index local 'character' (a nil value)
stack traceback:
	__space-exploration__/control.lua:600: in function 'is_character_passenger'
	__space-exploration__/control.lua:662: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>
```

**Comment by jackpassero** [comment]
![image](https://user-images.githubusercontent.com/50419809/101912404-be7d8480-3bd2-11eb-939e-ff23d93304ad.png)

**Comment by dennes544** [comment]
Having same issue on [0.6.86] version
On another planet the pyramid is invisible, and when i step in it or fly above it with jetpack same crash happens

201.943 Error MainLoop.cpp:1284: Exception at tick 25389337: The mod Space Exploration (0.6.86) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event space-exploration::on_player_changed_position (ID 85)
__space-exploration__/control.lua:775: attempt to index field 'character' (a nil value)
stack traceback:
__space-exploration__/control.lua:775: in function 'callback'
__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>
201.943 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Space Exploration (0.6.86) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event space-exploration::on_player_changed_position (ID 85)
__space-exploration__/control.lua:775: attempt to index field 'character' (a nil value)
stack traceback:
__space-exploration__/control.lua:775: in function 'callback'
__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>"
201.943 Info ServerMultiplayerManager.cpp:795: updateTick(25389337) changing state from(InGame) to(Failed)

**Comment by InappropriatePenguin** [comment]
Can you share your savefile with your character near the problematic area?

**Comment by dennes544** [comment]
Sure, here is link https://drive.google.com/file/d/1Gghp1k7KyUcVceXEt7pzpKTaqqVvHsCp/view?usp=sharing
![image](https://user-images.githubusercontent.com/4429342/191078522-9030dbb1-778b-4597-b36c-1a6a10f9abd9.png)

Pyramid should be in red circle, but it's not visible. Most of times i can enter insyde, but sometimes it crashes. And it crashes every time when i fly over it with jetpack. I checked on another planet, called Dionysus (it have pyramid too and its visible), there is no crash if i enter it, or fly over it

**Comment by dennes544** [comment]
Also, it becomes visible, when crash window opens
<img width="822" alt="image" src="https://user-images.githubusercontent.com/4429342/191080192-cfba9563-cefc-46bd-8553-a4957523b571.png">

**Comment by InappropriatePenguin** [comment]
Thanks for the additional context. It turns out your issue is actually closely linked to #239. In your screenshot, there's a core seam that spawned close to the position of pyramid. That core seam getting created there destroyed the pyramid, which is why it's not visible.

When you walk into the pyramid's expected location, SE searches for a pyramid, doesn't find one, and then tries to create a new one. When it does, it presumably destroys overlapping entities, which _happen to include your character_. That's how you end up with an invalid character in this case.

The issue I linked above now has a pending fix. Once it's out, you can delete the surface from the Universe Explorer and view it again to recreate it. The pyramid structure will survive this time and core seam will be sealed.

**Comment by dennes544** [comment]
Ok, any ETA's?

**Comment by InappropriatePenguin** [comment]
I had _just_ implemented the fix, so it'll depend on when Earendel is available to review it/make a new release. It could happen later today, but it could also take a few days.

**Comment by dennes544** [comment]
Ok, big thanks to you :)
