### ISSUE TITLE
Incorrect translation of Space Exploration mod into Russian

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [EarendelDevelopers/factorio-mods#64]
It is necessary to make changes to the localization of the mod into Russian. Namely in the line "space-exploration =" of the section "[mod-name]". The name of the mod remains in its original form, it makes no sense to translate it into another language. In any case, there is no need to translate it into Russian.
```
[mod-name]
space-exploration=Space Exploration
```

**Comment by AartBluestoke** [comment]
@EarendelGames should this be on https://github.com/EarendelDevelopers/factorio-mods/issues/27 ?

**Comment by heinwessels** [comment]
This has been changed to this at some point:
```
[mod-name]
space-exploration=Space Exploration (Исследование космоса)
```
