### ISSUE TITLE
[Space Exploration] Transport belt upgrade to space belt.

### ISSUE THREAD

**Issue by woutershep** [EarendelDevelopers/factorio-mods#65]
I cannot make an upgrade planner for a yellow belt to a space belt upgrade.
Despite the space belt being placeable on nauvis and working just fine to move items.
I suspect one of these two is an error.
![2021-01-03-210113_459x442_scrot](https://user-images.githubusercontent.com/11578180/103487580-d8dc0400-4e06-11eb-9511-eb59404fbe70.png)

In the same vein space belts cant overwrite regular belts by clicking on them. ('Transport belt is in the way.')
I suspect this ties into the same upgrade logic but i'm not entirely sure.

**Comment by AartBluestoke** [comment]
upgrades can not occur between things with different collision masks. (this hurts SE as nothing planet side can be upgraded to their space variants, including belts and rails) 

this "feature" was hard coded in the game engine as there are too many corner cases where you could end up with potentially illegal objects.

**Comment by AartBluestoke** [comment]
closing as "can't fix, but would love to".
