### ISSUE TITLE
any time i click on space explorer. crashes the whole game!!!

### ISSUE THREAD

**Issue by mansoorafm** [EarendelDevelopers/factorio-mods#66]
The mod Space Exploration (0.5.35) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::on_lua_shortcut (ID 35)
__space-exploration__/scripts/zonelist.lua:511: attempt to index field '?' (a nil value)
stack traceback:
	__space-exploration__/scripts/zonelist.lua:511: in function 'gui_update_zone_content'
	__space-exploration__/scripts/zonelist.lua:350: in function 'gui_update_selected'
	__space-exploration__/scripts/zonelist.lua:236: in function 'gui_update'
	__space-exploration__/scripts/zonelist.lua:191: in function 'gui_open'
	__space-exploration__/scripts/zonelist.lua:1064: in function 'toggle_main_window'
	__space-exploration__/scripts/zonelist.lua:1280: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by mansoorafm** [comment]
please fix this problem as it continues to be an issue. i cant go anywhere and explorer more planets. thanks

**Comment by mansoorafm** [comment]
The mod Space Exploration (0.5.37) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::se-universe-explorer (ID 184)
__space-exploration__/scripts/zonelist.lua:511: attempt to index field '?' (a nil value)
stack traceback:
	__space-exploration__/scripts/zonelist.lua:511: in function 'gui_update_zone_content'
	__space-exploration__/scripts/zonelist.lua:350: in function 'gui_update_selected'
	__space-exploration__/scripts/zonelist.lua:236: in function 'gui_update'
	__space-exploration__/scripts/zonelist.lua:191: in function 'gui_open'
	__space-exploration__/scripts/zonelist.lua:1064: in function 'toggle_main_window'
	__space-exploration__/scripts/zonelist.lua:1288: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by mansoorafm** [comment]
The mod Space Exploration (0.5.37) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event space-exploration::se-universe-explorer (ID 184)
__space-exploration__/scripts/zonelist.lua:511: attempt to index field '?' (a nil value)
stack traceback:
	__space-exploration__/scripts/zonelist.lua:511: in function 'gui_update_zone_content'
	__space-exploration__/scripts/zonelist.lua:350: in function 'gui_update_selected'
	__space-exploration__/scripts/zonelist.lua:236: in function 'gui_update'
	__space-exploration__/scripts/zonelist.lua:191: in function 'gui_open'
	__space-exploration__/scripts/zonelist.lua:1064: in function 'toggle_main_window'
	__space-exploration__/scripts/zonelist.lua:1288: in function 'callback'
	__space-exploration__/scripts/event.lua:15: in function <__space-exploration__/scripts/event.lua:13>

**Comment by mansoorafm** [comment]
Mod Author: please look into this problem.
This problem is persisting. I am not able to go to other planets.
I am not able to further any research.
Thanks and will appreciate your support.

**Comment by InappropriatePenguin** [comment]
@mansoorafm, is this still an issue you’re having?

**Comment by mansoorafm** [comment]
not any more.
but this was an issue long time ago.

**Comment by InappropriatePenguin** [comment]
Alright, great. Going to close this issue then.
