### ISSUE TITLE
Save a surface lock time to spaceship on launch. Can't land until set time is exceeded.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#68]
Launching an immediatly landing a spaceship in the next tick can potentially cause issues with the 'disable for one tick' thing inserters have going on.

On launch set a surface lock timeout to game.tick + 60. Disable ability to land until the timer has expired.

**Comment by Derunih** [comment]
No longer an issue, due to triggered integrity checks
