### ISSUE TITLE
Jetpack gets you stuck in walls.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#69]
Flying at a spaceship can leave you stuck in walls. There's already some code to find a safe landing position. It's unclear if it is the collosionless cahracter to normal character transition, or a consequence or the zero-altitude character with collision being teleported into the wall. If it is the latter then there's the old issue of finding a safe position becuase the character probably intersects that position and makes it invalid and could make a weird jittering behaviour.

**Comment by InappropriatePenguin** [comment]
Should be resolved in 0.3.6.
