### ISSUE TITLE
Add destination selection to space capsules.

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#7]
Destination options should be:

If in orbit around a planet or moon:
  Add the planet/moon below. 
  Add the orbit of the next body up and down the planet gravity well (planet is at the bottom outer moon is at the top)
  If already at the top of the gravity well (or an asteroidbelt), add the next outer body of the star's next children (asteroid field or a planets outer most moon).

If orbit of a star add the outer most moon of the first planet.

If in an asteroid field, add the outer most body of the 4 closest stars. (Last planet, last moon, or an asteroid belt if that is the last child). 

This basically allows you to hop between orbits to get home but it takes a few hops / orbital transfer / slingshots.

Emergancy burn to homeworld. This option is available from anywhere and is direct but there is a high probability that the capsule is destroyed on 'landing' (crashing).

**Comment by Brickcaster** [comment]
Any particular reason the capsule can't simply go straight home?  Does it need refueling?  Seems unnecessary to force the player to visit multiple surfaces if there's no reason not to immediately take off again.

**Comment by EarendelGames** [comment]
You can go straight home with the emergency burn. It is to let people move around space zones without it being a practical logistic option.
