### ISSUE TITLE
Reduce spaceship GUI update interval

### ISSUE THREAD

**Issue by EarendelGames** [EarendelDevelopers/factorio-mods#75]
"if you keep the spaceship console window open while in flight, it drops UPS significantly - to the extent of 60fps/ups to 45"
It is probably still per tick. Change to update every 30 ticks.

**Comment by daviscook477** [comment]
resolved. configurable with tick_interval property in spaceship_gui.lua. I think I set it to something like every 10 ticks or maybe 20.
