### ISSUE TITLE
Universe Explorer Filter or Sort by if surface is generated

### ISSUE THREAD

**Issue by daviscook477** [EarendelDevelopers/factorio-mods#93]
Players wish to cleanup generated surfaces that they aren't using.
This is not very possible in the current universe explorer because they have to go through all zones (of which there are a *lot* late in the game when UPS becomes a concern) to see if the surface is generated.

Using a flag (like the player-has-visited, or has-cargo-rocket-silo, or has-landing-pad) could work. Or another column for sorting.  Just ideas for how to address.

**Comment by InappropriatePenguin** [comment]
@daviscook477, do you think this is sufficiently addressed by the zone priority toggle?

**Comment by InappropriatePenguin** [comment]
Resolved by UE redesign in 0.6.88.
